---
title: "Demographic statistics for Alzheimer's Disease in the US"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
runtime: shiny
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(flexdashboard)

library(shiny)
library(readxl)
library(tidyverse)
library(usmap)
library(plotly)
library(ggplot2)
```

```{r, message = FALSE, warning = FALSE}
shiny_data =
  read_csv("./Data/geo_data.csv") |>
  pivot_longer(
    death_rate:obesity_rate,
    names_to = "type",
    values_to = "value") |>
  mutate(type =
    case_match(
      type,
      "death_rate" ~ "Death rate",
      "gdp" ~ "GDP",
      "pce" ~ "Consumption expenditures",
      "rpp" ~ "Price parities",
      "employment" ~ "Employment",
      "hc_exp" ~ "Healthcare expenditures",
      "income" ~ "Personal income",
      "edu_level" ~ "Education level",
      "diabetes_rate" ~ "Diabetes rate",
      "cardio_rate" ~ "Cardio rate",
      "smoke_rate" ~ "Smoke rate",
      "elder_rate" ~ "Elder rate",
      "obesity_rate" ~ "Obesity rate"))
```

Column {.sidebar}
-----------------------------------------------------------------------
```{r}
selectInput(
  "year", 
  label = h3("Select year"),
  choices = c(2018, 2019, 2020, 2021), selected = "2018")

geo_type = unique(pull(shiny_data, type))

radioButtons(
  "geo_type", 
  label = h3("Select Category"),
  choices = geo_type, selected = "Death rate")


```

Row
-----------------------------------------------------------------------
### Demographic visualizations
```{r}
renderPlotly({
  ggplotly(plot_usmap(data = shiny_data |>
                        filter(year == input$year,
                               type == input$geo_type) |>
                        mutate(state = order(state),
                               fips = pull(statepop, fips),
                               abbr = pull(statepop, abbr)),
           values = "value",
           labels = TRUE))
  })
```