---
title: "Proposal"
output: github_document
---

# The motivation for this project
Alzheimer’s disease is an irreversible, progressive brain disorder affecting more than 6.5 million Americans that slowly destroys memory and thinking skills and, eventually, the ability to carry out simple tasks. However, existing drugs only treat the symptoms of Alzheimer’s disease. They do not treat the root cause of the disease and do not slow down how quickly it gets worse. To date, there hasn’t been a new drug approved for Alzheimer’s disease in 20 years. This year is an important year for AD because a breakthrough occurs in AD treatment: two promising drugs, Leqembi and Donanmab, for treating Alzheimer's disease bring fresh hope. Leqembi, the first treatment that shows an unequivocal slowing of decline in Alzheimer’s disease, is fully approved by FDA in July 2023. Donanemab is widely expected to be granted full FDA approval within the next year. These two medications are both with impressive Phase III clinical trial results. They represent an important advancement in the ongoing fight to effectively treat Alzheimer’s disease and could be the beginning of the end of Alzheimer's disease. 

# The intended final products
Our project culminates in the creation of a comprehensive website serving as the central hub for all project-related information and tools. The website will feature:

 Homepage Overview: A welcoming homepage providing a succinct overview of the project. It will include essential information such as the project's objectives, motivation, the initial questions we aim to address, and a brief intro of our team members. Additionally, a screencast will offer visitors a guided tour of our project, encapsulating our journey from conception to realization.
Data Exploration: A dedicated section for our data sources and exploratory data analysis (EDA), offering insights into the foundational data that informs our research and models.

The website will also host a suite of interactive tools, visualizations and statistical models focusing on three key topics:
Geographical Analysis Tool: An interactive 'Shiny' application that maps the distribution of Alzheimer's Disease (AD) patients across the United States, allowing users to identify patterns and hotspots.
Risk Factor Analysis: We will develop statistical models to analyze the risk factors associated with Alzheimer's Disease, providing valuable insights into prevention and early detection strategies.
Clinical Trials analysis: Alzheimer’s drug development pipeline. A spotlight on two recently released medications will give a further comparison of efficacy, side effects, and other critical metrics, empowering stakeholders with data-driven insights.


# Anticipated Data Sources


# The planned analyses / visualizations / coding challenges


# The planned timeline

| Date | Description | 
|------|------|
| Nov 13-17 | Project review meeting  | 
| Nov 18-21 | Prepare and build the intended website  |
| Nov 27-30 | Complete Part I  |
| Dec 1-4 | Complete Part II  |
| Dec 5-7 | Complete Part III  |
| Dec 8-9 | Review and check the project, complete screencast and peer assessment  |