<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Project report - Alzheimer’s Disease: New Hope</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.6.3/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="Report.html">Report</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="Introduction.html">Introduction</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Data.html">Data Sources</a>
    </li>
    <li>
      <a href="EDA.html">Exploratory Analysis</a>
    </li>
    <li>
      <a href="Preliminary_analysis.html">Preliminary Analysis</a>
    </li>
  </ul>
</li>
<li>
  <a href="Model.html">Model</a>
</li>
<li>
  <a href="Clinical_trials.html">Clinical Trials</a>
</li>
<li>
  <a href="Conclusion.html">Conclusion</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Shiny
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="https://yigebian.shinyapps.io/Demographic_shiny/">Demographic</a>
    </li>
    <li>
      <a href="https://yigebian.shinyapps.io/ClinicalTrials_shiny/">Clinical Trials</a>
    </li>
  </ul>
</li>
<li>
  <a href="mailto:&lt;yb2591@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-github fa-lg"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="https://github.com/MiaYum/Alzheimers_Disease_New_Hope">Website Repository</a>
    </li>
    <li>
      <a href="https://github.com/YigeBian/Alzheimers_Disease_New_Hope_Shiny">Shiny Repository</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Project report - Alzheimer’s Disease: New
Hope</h1>

</div>


<p><strong>Mia Yu, Aiying Huang, Kairui Wang, Yige Bian, Eunice
Wang</strong></p>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>In the quiet twilight of memory, where the essence of a person’s life
- their joys, sorrows, and triumphs - slowly dims, lies the profound
tragedy of Alzheimer’s disease. It’s a realm where the familiar contours
of identity are relentlessly eroded, not by the passage of time, but by
an insidious ailment that disassembles the core of who they are. Each
forgotten name, each lost memory, is a star winking out in the galaxy of
a person’s life story, leaving behind a haunting void where once there
was a rich tapestry of experiences and connections.</p>
<p><img src="project_image/AD-motivation-pic.jpg" style="width:85%"></p>
<div id="motivation" class="section level2">
<h2>Motivation</h2>
<p>Alzheimer’s disease is an irreversible, progressive brain disorder
affecting more than 6.5 million Americans that slowly destroys memory
and thinking skills and, eventually, the ability to carry out simple
tasks. However, existing drugs only treat the symptoms of Alzheimer’s
disease. They do not treat the root cause of the disease and do not slow
down how quickly it gets worse. To date, there hasn’t been a new drug
approved for Alzheimer’s disease in 20 years. 2023 is an important year
for AD because a breakthrough occurs in AD treatment: two promising
drugs, Leqembi and Donanmab, for treating Alzheimer’s disease bring
fresh hope. Leqembi, the first treatment that shows an unequivocal
slowing of decline in Alzheimer’s disease, is fully approved by FDA in
July 2023. Donanemab is widely expected to be granted full FDA approval
within the next year. These two medications are both with impressive
Phase III clinical trial results. They represent an important
advancement in the ongoing fight to effectively treat Alzheimer’s
disease and could be the beginning of the end of Alzheimer’s
disease.</p>
<p>Our project is driven by the desire to deeply understand Alzheimer’s
disease in its entirety - its distribution, associated factors, and the
transformative potential of these new drugs. We aim to explore how these
advancements might alter the course of Alzheimer’s.</p>
</div>
<div id="related-work" class="section level2">
<h2>Related work</h2>
<p>The <a
href="https://www.alz.org/alzheimers-dementia/facts-figures">“Alzheimer’s
Disease Facts and Figures 2023”</a> report from the Alzheimer’s
Association reveals the growing prevalence of Alzheimer’s disease in the
United States. Over 6 million Americans are currently living with
Alzheimer’s, with projections suggesting this number could rise to about
13 million by 2050. This disease, a leading cause of death among
seniors, has significant health, societal, and economic impacts, with
mortality rates exceeding those of breast and prostate cancer
combined.</p>
<p>Our research focuses on the complex relationship between Alzheimer’s
Disease and its risk factors as highlighted in <a
href="https://www.alzinfo.org/articles/non-genetic-risk-factors/">existing
studies</a>. Key elements include: (1) Age-related brain changes like
neuron degeneration and protein build-up; (2) Educational attainment,
potentially offering neural protection; (3) Cardiovascular risk factors
akin to heart health impacting Alzheimer’s risk; (4) The link between
diabetes and cognitive decline; (5) Socioeconomic factors influencing
lifestyle and healthcare access, thereby affecting Alzheimer’s risk.</p>
<p>In the dynamic landscape of Alzheimer’s disease research,
ClinicalTrials.gov stands as a comprehensive repository, detailing
ongoing clinical trials . Furthermore, Phase III clinical trials of two
latest promising drugs Lecanemab and Donanemab were extensively
documented in journal articles, have garnered significant attention for
their in-depth investigation.</p>
</div>
<div id="initial-questions" class="section level2">
<h2>Initial Questions</h2>
<p>From the available data we are interested in answering the following
questions:</p>
<ul>
<li><p>Regarding Alzheimer Facts and Influencing Factors</p>
<ul>
<li><p>How does the distribution and prevalence of Alzheimer’s disease
vary across the United States, and what are the key factors influencing
these patterns?</p></li>
<li><p>How can our data science models predict future trends in
mortality rates of Alzheimer’s patients across different states, and how
might these predictions inform targeted interventions and resource
allocation to mitigate the impact of Alzheimer’s disease?</p></li>
</ul></li>
<li><p>Regarding Pipeline and Clinical Trials of New Alzheimer Drugs</p>
<ul>
<li><p>How can we provide a comprehensive and detailed overview of the
current Alzheimer’s drug trials in the U.S., encompassing their stages,
approaches, and geographical distribution?</p></li>
<li><p>How do Lecanemab and Donanemab, the newly FDA-approved
Alzheimer’s drugs, compare in terms of their development, efficacy, and
potential impact?</p></li>
</ul></li>
</ul>
</div>
</div>
<div id="analysis" class="section level1">
<h1>Analysis</h1>
<div id="data-sources" class="section level2">
<h2>Data Sources</h2>
<div id="associated-factors-datasets" class="section level3">
<h3>Associated Factors Datasets</h3>
<p>To study the complex interplay of factors contributing to Alzheimer’s
Disease, we have sourced a diverse range of datasets, including age,
socioeconomic status, healthcare access, education level, etc. We
collected data from authoritative and reliable sources such as
government website and professional institude. The final data for
analysis is obtained by merging these Alzheimer’s Disease related
datasets. The cleaning process include variable selection, converting
variable to the type we need, and transforming the dataframe to tidy
format. The details of importing and cleaning of all datasets are as
following:</p>
<ul>
<li><p>The first dataset <code>death_rate</code> contains the mortality
of Alzheimer’s Disease in each state from 2014 to 2021, which can be
accessed from <a
href="https://www.cdc.gov/nchs/pressroom/sosmap/alzheimers_mortality/alzheimers_disease.htm">CDC</a>.</p></li>
<li><p><code>econdata</code> dataset contains the economic status of
each state from 2008 to 2021, including GDP, income, price index,
expenditure on healthcare etc. The data is downloaded from <a
href="https://apps.bea.gov/iTable/?reqid=70&amp;step=1&amp;acrdn=2&amp;_gl=1*14uawee*_ga*MzQ4ODY3MjA1LjE3MDEzMTIzMDc.*_ga_J4698JNNFT*MTcwMTMxMjMwNi4xLjEuMTcwMTMxMjM4OS4wLjAuMA..#eyJhcHBpZCI6NzAsInN0ZXBzIjpbMSwyOSwyNSwzMSwyNiwyNywzMF0sImRhdGEiOltbIlRhYmxlSWQiLCI2MDAiXSxbIk1ham9yX0FyZWEiLCIwIl0sWyJTdGF0ZSIsWyIwIl1dLFsiQXJlYSIsWyJYWCJdXSxbIlN0YXRpc3RpYyIsWyItMSJdXSxbIlVuaXRfb2ZfbWVhc3VyZSIsIkxldmVscyJdLFsiWWVhciIsWyItMSJdXSxbIlllYXJCZWdpbiIsIi0xIl0sWyJZZWFyX0VuZCIsIi0xIl1dfQ==">Bureau
of Economic Analysis</a>.</p></li>
<li><p><code>edu_level</code> dataset contains the percentage of
population obtained Bachelor’s Degree or Higher in each state from 2018
to 2021. The data is extracted from <a
href="https://fred.stlouisfed.org/release/tables?rid=330&amp;eid=391444&amp;od=2018-01-01#">Federal
Reserve Economic Data</a>.</p></li>
<li><p><code>diabetes</code> dataset contains the rate of diabetes by
state from 2018 to 2021. The data can be accessed <a
href="https://www.kff.org/other/state-indicator/adults-with-diabetes/?currentTimeframe=1&amp;sortModel=%7B%22colId%22:%22Location%22,%22sort%22:%22asc%22%7D">here</a>.</p></li>
<li><p><code>smoke</code> dataset contains the rate of smoking by state.
The sources of the data are <a
href="https://www.cdc.gov/tobacco/data_statistics/fact_sheets/adult_data/cig_smoking/index.htm">CDC</a>
and <a
href="https://www.kff.org/other/state-indicator/smoking-adults-by-sex/?currentTimeframe=2&amp;sortModel=%7B%22colId%22:%22Location%22,%22sort%22:%22asc%22%7D">KFF</a>.</p></li>
<li><p><code>Cardiovascular Disease</code> dataset contains the
Cardiovascular Disease rate, and the data can be accessed <a
href="https://www.kff.org/other/state-indicator/percent-of-adults-with-cardiovascular-disease-by-sex/?currentTimeframe=1&amp;sortModel=%7B%22colId%22:%22Location%22,%22sort%22:%22asc%22%7D">here</a>.</p></li>
<li><p><code>age_over_65</code> dataset contains the percentage of
elderly people (&gt;65 years old). This data is extracted from <a
href="https://data.census.gov/table/ACSDP1Y2021.DP05?g=010XX00US$0400000&amp;moe=false">Census
Bureau</a> and <a
href="https://www.prb.org/resources/which-us-states-are-the-oldest/">PRB</a>.</p></li>
<li><p><code>obesity</code> dataset contains the percent of adults aged
18 years and older who have obesity in each state, and the data can be
accessed from <a
href="https://nccd.cdc.gov/dnpao_dtm/rdPage.aspx?rdReport=DNPAO_DTM.ExploreByTopic&amp;islClass=OWS&amp;islTopic=&amp;go=GO">CDC</a>.</p></li>
</ul>
<pre class="r"><code>death_rate = 
  read_csv(&quot;./Data/death_rate.csv&quot;) |&gt;
  janitor::clean_names() |&gt;
  rename(death_rate = rate) |&gt;
  select(state, year, death_rate) |&gt;
  filter(year &gt;= 2018) |&gt;
  arrange(state, year)

econ_data = 
  read_csv(&quot;./Data/econdata.csv&quot;) |&gt;
  janitor::clean_names() |&gt;
  select(geo_name, description, x2018:x2021) |&gt;
  mutate(description = 
           case_match(
             description,
             &quot;GDP&quot;~&quot;gdp&quot;,
             &quot;PCE&quot;~&quot;pce&quot;,
             &quot;Regional price parities&quot;~&quot;rpp&quot;,
             &quot;employment&quot;~&quot;employment&quot;,
             &quot;healthcare expenditure&quot;~&quot;hc_exp&quot;,
             &quot;personal income&quot;~&quot;income&quot;,
             &quot;population&quot;~&quot;population&quot;)) |&gt;
  pivot_longer(
    x2018:x2021,
    names_to = &quot;year&quot;,
    values_to = &quot;value&quot;
  ) |&gt;
  pivot_wider(
    names_from = &quot;description&quot;,
    values_from = &quot;value&quot;
  ) |&gt;
  rename(state = geo_name) |&gt;
  mutate(year = as.numeric(str_replace(year, &quot;x&quot;, &quot;&quot;)),
         gdp = gdp/(population/1000000),
         pce = pce/(population/1000000),
         employment = round(employment/(population), 4),
         hc_exp = hc_exp/(population/1000000),
         income = income/(population/1000000),
         ) |&gt;
  select(-population) |&gt;
  arrange(state, year)

edu_level = 
  read_excel(&quot;./Data/edu_level.xlsx&quot;) |&gt;
  janitor::clean_names() |&gt;
  select(state, x2018:x2021) |&gt;
  pivot_longer(
    x2018:x2021,
    names_to = &quot;year&quot;,
    values_to = &quot;edu_level&quot;
  ) |&gt;
  mutate(year = as.numeric(str_replace(year, &quot;x&quot;, &quot;&quot;)),
         edu_level = edu_level/100) |&gt;
  arrange(state, year)

diabetes_rate = 
  read_excel(&quot;./Data/diabetes.xlsx&quot;, range = &quot;A1:C205&quot;) |&gt;
  janitor::clean_names() |&gt;
  rename(diabetes_rate = diabetes_proportion) |&gt;
  mutate(diabetes_rate = round(as.numeric(diabetes_rate), 3),
         year = as.numeric(year)) |&gt;
  arrange(state, year)

cardio_rate = 
  read_excel(&quot;./Data/Cardiovascular Disease.xlsx&quot;, range = &quot;A1:E52&quot;) |&gt;
  janitor::clean_names() |&gt;
  pivot_longer(
    x2018:x2021,
    names_to = &quot;year&quot;,
    values_to = &quot;cardio_rate&quot;
  ) |&gt;
  mutate(year = as.numeric(str_replace(year, &quot;x&quot;, &quot;&quot;))) |&gt;
  arrange(state, year)

smoke_rate =
  read_excel(&quot;./Data/smoke.xlsx&quot;) |&gt;
  janitor::clean_names() |&gt;
  pivot_longer(
    x2018:x2021,
    names_to = &quot;year&quot;,
    values_to = &quot;smoke_rate&quot;
  ) |&gt;
  mutate(year = as.numeric(str_replace(year, &quot;x&quot;, &quot;&quot;)),
         smoke_rate = smoke_rate/100) |&gt;
  arrange(state, year)

elderly_rate = read_excel(&quot;./Data/age_over_65/age_over_65.xlsx&quot;) |&gt;
  janitor::clean_names() |&gt;
  pivot_longer(
    x2018:x2021,
    names_to = &quot;year&quot;,
    values_to = &quot;elder_rate&quot;
  ) |&gt;
  mutate(year = as.numeric(str_replace(year, &quot;x&quot;, &quot;&quot;))) |&gt;
  arrange(state, year)

obesity_rate = read_csv(&quot;./Data/obesity.csv&quot;) |&gt;
  janitor::clean_names() |&gt;
  pivot_longer(
    x2018:x2021,
    names_to = &quot;year&quot;,
    values_to = &quot;obesity_rate&quot;
  ) |&gt;
  mutate(year = as.numeric(str_replace(year, &quot;x&quot;, &quot;&quot;))) |&gt;
  arrange(state, year)</code></pre>
<pre class="r"><code>geo_data = left_join(death_rate, econ_data, by = c(&quot;state&quot;, &quot;year&quot;)) |&gt;
  left_join(edu_level, by = c(&quot;state&quot;, &quot;year&quot;)) |&gt;
  left_join(diabetes_rate, by = c(&quot;state&quot;, &quot;year&quot;)) |&gt;
  left_join(cardio_rate, by = c(&quot;state&quot;, &quot;year&quot;)) |&gt;
  left_join(smoke_rate, by = c(&quot;state&quot;, &quot;year&quot;)) |&gt;
  left_join(elderly_rate, by = c(&quot;state&quot;, &quot;year&quot;)) |&gt;
  left_join(obesity_rate, by = c(&quot;state&quot;, &quot;year&quot;))</code></pre>
<p>These datasets were tidied and merged as <code>geo_data</code> for
our future study. The final <code>geo_data</code> contains 204 and 15
variables, including state, year, death_rate, gdp, pce, rpp, employment,
hc_exp, income, edu_level, diabetes_rate, cardio_rate, smoke_rate,
elder_rate, obesity_rate</p>
<pre class="r"><code>write.csv(geo_data, &quot;./Data/geo_data.csv&quot;, row.names = FALSE)</code></pre>
</div>
<div id="clinical-trials-data" class="section level3">
<h3>Clinical Trials data</h3>
<p>Clinicaltrials.gov provided complete and detailed information of all
current Alzheimer’s disease drugs. Clinical Trials data is directly
downloaded from <a
href="https://clinicaltrials.gov/search?cond=Alzheimer">clinicaltrials.gov</a>.</p>
<pre class="r"><code>CT_data = 
  read_csv(&quot;./Data/ClinicalTrials_raw_data.csv&quot;) |&gt;
  janitor::clean_names() |&gt;
  select(-study_title, -acronym, -study_results, -conditions, -brief_summary, -primary_outcome_measures, -secondary_outcome_measures, -other_outcome_measures, -study_design, -other_i_ds, - primary_completion_date, -first_posted, -results_first_posted, -last_update_posted)</code></pre>
<p>The raw data is too complicated with redundant information, so we did
an initial variable selection to omit useless variables. There are a
total of 3026 and 15 variables. Variables and description is listed
below:</p>
<ul>
<li><p><code>nct_number</code>: Unique Identification of clinical
trials</p></li>
<li><p><code>study_url</code>: Website address for more details of the
study</p></li>
<li><p><code>study_status</code>: Study status</p></li>
<li><p><code>interventions</code>: Intervention methods of
study</p></li>
<li><p><code>sponsor</code>: Study sponsor</p></li>
<li><p><code>collaborators</code>: Study collaborator</p></li>
<li><p><code>sex</code>: Gender of study participants (include “MALE”,
“FEMALE”, “ALL”, “OBSERVATIONAL”, and missing value)</p></li>
<li><p><code>age</code>: Age of study participants (include combination
of Chiled, Adult, Oler Adult, and missing value)</p></li>
<li><p><code>phases</code>: Phases of the study</p></li>
<li><p><code>enrollment</code>: Number of Participants enrolled in the
study</p></li>
<li><p><code>funder_type</code>: Type of sponsor</p></li>
<li><p><code>study_type</code>: Type of study (“INTERVENTIONAL”,
“OBSERVATIONAL”, “EXPANDED_ACCESS”, and missing value)</p></li>
<li><p><code>start_date</code>: Start date of study</p></li>
<li><p><code>completion_date</code>: Completion date of study</p></li>
<li><p><code>locations</code>: Location(s) of study (Locations were
divided by “|” for study conducted in more than one location)</p></li>
</ul>
<p>Data for further investigation on two latest drugs Lecanemab and
Donanemab are from their published Phase III study results. Relevant
website could be accessd from <a
href="https://www.nejm.org/doi/full/10.1056/NEJMoa2212948?downloadfile=downloadFigures#article_supplementary_material">Lecanemab</a>
and <a
href="https://jamanetwork.com/journals/jama/article-abstract/2807533">Donanemab</a>.
Both study contians data for participants basic information, adverse
events statistics, survival analysis and treatment evaluation.</p>
<pre class="r"><code># Safety data for Lecanemab
lec_safety =
  readxl::read_excel(&quot;data/Lecanemab.xlsx&quot;,sheet=&quot;safety&quot;, range = &quot;A1:C5&quot;)

# Adverse Events data for Lecanemab
lec_AE =
  readxl::read_excel(&quot;data/Lecanemab.xlsx&quot;,sheet=&quot;AE&quot;, range = &quot;A1:C10&quot;)

# Treatment evluation data for Lecanemab
lec_result =
  readxl::read_excel(&quot;data/Lecanemab.xlsx&quot;,sheet=&quot;safety&quot;, range = &quot;A1:H15&quot;)

# Safety data for Donanemab
don_safety =
  readxl::read_excel(&quot;data/Donanemab.xlsx&quot;,sheet=&quot;safety&quot;, range = &quot;A1:C5&quot;)

# Adverse Events data for Donanemab
don_AE =
  readxl::read_excel(&quot;data/Donanemab.xlsx&quot;,sheet=&quot;AE&quot;, range = &quot;A1:C10&quot;)

# Hazard ratio analysis data for Donanemab
don_hazard =
  readxl::read_excel(&quot;data/Donanemab.xlsx&quot;,sheet=&quot;K-M&quot;, range = &quot;A1:D17&quot;)

# Treatment evluation data for Donanemab
don_result =
  readxl::read_excel(&quot;data/Donanemab.xlsx&quot;,sheet=&quot;safety&quot;, range = &quot;A1:H33&quot;)</code></pre>
</div>
</div>
<div id="exploratory-analysis" class="section level2">
<h2>Exploratory Analysis</h2>
<div id="shiny-app" class="section level3">
<h3>Shiny App</h3>
<p>The prevalence and mortality rates of Alzheimer’s Disease, along with
other pertinent factors, exhibit significant variation across different
states and over various years. To effectively visualize and have a
direct overview of these geographical and temporal trends, we have
developed a Shiny app. The following screenshot offers a glimpse into
the app’s capabilities, and the full dashboard can be accessed
[here].</p>
<p><img src="project_image/demo_shiny.jpg" style="width:75%"></p>
</div>
<div id="data-overview" class="section level3">
<h3>Data Overview</h3>
<pre class="r"><code>data = read_csv(&quot;./Data/geo_data.csv&quot;)
# 1. Descriptive statistics table for all variables
skimr::skim(data)</code></pre>
<table>
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">204</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">15</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">14</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<colgroup>
<col width="19%" />
<col width="13%" />
<col width="19%" />
<col width="5%" />
<col width="5%" />
<col width="8%" />
<col width="12%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">state</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">20</td>
<td align="right">0</td>
<td align="right">51</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<colgroup>
<col width="12%" />
<col width="9%" />
<col width="12%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="9%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">year</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">2019.50</td>
<td align="right">1.12</td>
<td align="right">2018.00</td>
<td align="right">2018.75</td>
<td align="right">2019.50</td>
<td align="right">2020.25</td>
<td align="right">2021.00</td>
<td align="left">▇▇▁▇▇</td>
</tr>
<tr class="even">
<td align="left">death_rate</td>
<td align="right">4</td>
<td align="right">0.98</td>
<td align="right">32.08</td>
<td align="right">8.69</td>
<td align="right">13.60</td>
<td align="right">25.90</td>
<td align="right">32.70</td>
<td align="right">37.90</td>
<td align="right">58.00</td>
<td align="left">▃▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">gdp</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">61397.29</td>
<td align="right">22766.78</td>
<td align="right">36958.76</td>
<td align="right">50478.65</td>
<td align="right">57614.92</td>
<td align="right">65740.82</td>
<td align="right">213334.66</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">pce</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">40289.62</td>
<td align="right">3973.64</td>
<td align="right">34085.58</td>
<td align="right">37609.41</td>
<td align="right">39756.63</td>
<td align="right">42098.30</td>
<td align="right">61372.54</td>
<td align="left">▇▇▂▁▁</td>
</tr>
<tr class="odd">
<td align="left">rpp</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">97.28</td>
<td align="right">7.06</td>
<td align="right">85.84</td>
<td align="right">91.68</td>
<td align="right">95.42</td>
<td align="right">102.31</td>
<td align="right">113.23</td>
<td align="left">▅▇▅▃▃</td>
</tr>
<tr class="even">
<td align="left">employment</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.62</td>
<td align="right">0.11</td>
<td align="right">0.47</td>
<td align="right">0.58</td>
<td align="right">0.61</td>
<td align="right">0.65</td>
<td align="right">1.30</td>
<td align="left">▇▃▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">hc_exp</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">7625.24</td>
<td align="right">1240.92</td>
<td align="right">5231.49</td>
<td align="right">6689.52</td>
<td align="right">7506.68</td>
<td align="right">8400.47</td>
<td align="right">11755.09</td>
<td align="left">▅▇▆▂▁</td>
</tr>
<tr class="even">
<td align="left">income</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">52537.53</td>
<td align="right">6160.77</td>
<td align="right">40646.56</td>
<td align="right">48262.55</td>
<td align="right">51807.00</td>
<td align="right">55718.68</td>
<td align="right">75357.47</td>
<td align="left">▃▇▃▁▁</td>
</tr>
<tr class="odd">
<td align="left">edu_level</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.33</td>
<td align="right">0.07</td>
<td align="right">0.21</td>
<td align="right">0.29</td>
<td align="right">0.32</td>
<td align="right">0.37</td>
<td align="right">0.64</td>
<td align="left">▅▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">diabetes_rate</td>
<td align="right">2</td>
<td align="right">0.99</td>
<td align="right">0.12</td>
<td align="right">0.02</td>
<td align="right">0.07</td>
<td align="right">0.10</td>
<td align="right">0.11</td>
<td align="right">0.13</td>
<td align="right">0.17</td>
<td align="left">▂▇▆▃▂</td>
</tr>
<tr class="odd">
<td align="left">cardio_rate</td>
<td align="right">2</td>
<td align="right">0.99</td>
<td align="right">0.07</td>
<td align="right">0.02</td>
<td align="right">0.04</td>
<td align="right">0.06</td>
<td align="right">0.07</td>
<td align="right">0.08</td>
<td align="right">0.13</td>
<td align="left">▂▇▅▁▁</td>
</tr>
<tr class="even">
<td align="left">smoke_rate</td>
<td align="right">2</td>
<td align="right">0.99</td>
<td align="right">0.15</td>
<td align="right">0.03</td>
<td align="right">0.06</td>
<td align="right">0.13</td>
<td align="right">0.15</td>
<td align="right">0.17</td>
<td align="right">0.25</td>
<td align="left">▂▇▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">elder_rate</td>
<td align="right">1</td>
<td align="right">1.00</td>
<td align="right">0.17</td>
<td align="right">0.02</td>
<td align="right">0.11</td>
<td align="right">0.16</td>
<td align="right">0.17</td>
<td align="right">0.18</td>
<td align="right">0.22</td>
<td align="left">▁▁▇▅▂</td>
</tr>
<tr class="even">
<td align="left">obesity_rate</td>
<td align="right">1</td>
<td align="right">1.00</td>
<td align="right">32.21</td>
<td align="right">4.06</td>
<td align="right">23.00</td>
<td align="right">29.35</td>
<td align="right">32.30</td>
<td align="right">35.20</td>
<td align="right">40.80</td>
<td align="left">▂▆▆▇▂</td>
</tr>
</tbody>
</table>
<p>The dataset contains 204 rows and 15 columns, covering a wide array
of variables categorized into several key areas:</p>
<p>Demographic and Economic Indicators: This includes data on the state,
year, death rate, Gross Domestic Product (<code>gdp</code>), Personal
Consumption Expenditure (<code>pce</code>), Regional Price Parity
(<code>rpp</code>), employment level (<code>employment_rate</code>),
healthcare expenditure (<code>hc_exp</code>), and income.</p>
<p>Public Health Metrics: The data provides detailed insights into
various health-related statistics, such as the diabetes rate,
cardiovascular disease rate, smoking rate, the proportion of the elderly
population, and the obesity rate.</p>
<pre class="r"><code>library(plotly)
missing_data &lt;- data |&gt;
  summarise_all(funs(sum(is.na(.)))) |&gt;
  gather(key = &quot;Variable&quot;, value = &quot;MissingValues&quot;) |&gt;
  mutate(Variable = fct_reorder(Variable, -MissingValues))

plot_ly(missing_data, x = ~Variable, y = ~MissingValues, type = &quot;bar&quot;, marker = list(color = &quot;rgba(55, 128, 191, 0.7)&quot;, line = list(color = &quot;rgba(55, 128, 191, 0.7)&quot;, width = 2))) |&gt;
  layout(title = &quot;Missing Data Visualization&quot;,
         xaxis = list(title = &quot;Variables&quot;),
         yaxis = list(title = &quot;Number of Missing Values&quot;))</code></pre>
<div class="plotly html-widget html-fill-item" id="htmlwidget-fbfe12f3cfc6226524db" style="width:90%;height:345.6px;"></div>
<script type="application/json" data-for="htmlwidget-fbfe12f3cfc6226524db">{"x":{"visdat":{"1754e2031649c":["function () ","plotlyVisDat"]},"cur_data":"1754e2031649c","attrs":{"1754e2031649c":{"x":{},"y":{},"marker":{"color":"rgba(55, 128, 191, 0.7)","line":{"color":"rgba(55, 128, 191, 0.7)","width":2}},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Missing Data Visualization","xaxis":{"domain":[0,1],"automargin":true,"title":"Variables","type":"category","categoryorder":"array","categoryarray":["death_rate","cardio_rate","diabetes_rate","smoke_rate","elder_rate","obesity_rate","edu_level","employment","gdp","hc_exp","income","pce","rpp","state","year"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Number of Missing Values"},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["state","year","death_rate","gdp","pce","rpp","employment","hc_exp","income","edu_level","diabetes_rate","cardio_rate","smoke_rate","elder_rate","obesity_rate"],"y":[0,0,4,0,0,0,0,0,0,0,2,2,2,1,1],"marker":{"color":"rgba(55, 128, 191, 0.7)","line":{"color":"rgba(55, 128, 191, 0.7)","width":2}},"type":"bar","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
<div id="missing-value-analysis" class="section level3">
<h3>Missing Value Analysis</h3>
<pre class="r"><code>data = data |&gt;
  drop_na(death_rate)</code></pre>
<p>From the above, we can see that there are 4 missing values in
<code>death_rate</code>. <code>diabetes_rate</code>,
<code>cardio_rate</code> and <code>smoke_rate</code> each have 2 missing
values. <code>elder_rate</code> and <code>obesity_rate</code> each have
1 missing value. The reason for missing values in
<code>death_rate</code> is that there is no available data for the
District of Columbia. Since <code>death_rate</code> is the predictor
variable of interest, we choose to directly delete all data for this
state. The remaining missing values are relatively few, and we choose to
directly delete rows containing missing values. In summary, because
there are not many missing values and they are not easily imputed, we
simply delete rows containing missing values.</p>
<pre class="r"><code># Explore distribution of results and consider potential transformations
# Create a histogram
plot_ly(data, x = ~death_rate, type = &quot;histogram&quot;, nbinsx = 30, marker = list(color = &quot;rgba(55, 128, 191, 0.7)&quot;, line = list(color = &quot;rgba(55, 128, 191, 0.7)&quot;, width = 2))) %&gt;%
  layout(title = &quot;Histogram of Death Rate&quot;)</code></pre>
<div class="plotly html-widget html-fill-item" id="htmlwidget-9fb6f0018c2185b229ef" style="width:90%;height:345.6px;"></div>
<script type="application/json" data-for="htmlwidget-9fb6f0018c2185b229ef">{"x":{"visdat":{"1754e7d4e55c7":["function () ","plotlyVisDat"]},"cur_data":"1754e7d4e55c7","attrs":{"1754e7d4e55c7":{"x":{},"nbinsx":30,"marker":{"color":"rgba(55, 128, 191, 0.7)","line":{"color":"rgba(55, 128, 191, 0.7)","width":2}},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"histogram"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Histogram of Death Rate","xaxis":{"domain":[0,1],"automargin":true,"title":"death_rate"},"yaxis":{"domain":[0,1],"automargin":true},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[44.899999999999999,44.600000000000001,50.799999999999997,46.799999999999997,27.5,25.300000000000001,26.800000000000001,26.399999999999999,33,32.299999999999997,32.700000000000003,30.5,38.899999999999999,39.5,45.600000000000001,43.200000000000003,37.100000000000001,37,40.600000000000001,39.5,29.600000000000001,33.399999999999999,36.899999999999999,32.600000000000001,18.5,18.100000000000001,20.300000000000001,21.199999999999999,32.700000000000003,25.899999999999999,35.100000000000001,29.699999999999999,19.199999999999999,18.300000000000001,19.800000000000001,19.600000000000001,46.5,41.899999999999999,45.899999999999999,44.5,20.199999999999999,19.100000000000001,22.800000000000001,23.899999999999999,35,33.200000000000003,36.700000000000003,40.5,25.300000000000001,24.5,28.699999999999999,26.600000000000001,33.399999999999999,31.600000000000001,34.299999999999997,29.699999999999999,31.699999999999999,29.199999999999999,31.899999999999999,28.199999999999999,23.600000000000001,21.899999999999999,25.300000000000001,22.600000000000001,32.5,32.100000000000001,32.299999999999997,32.700000000000003,42.200000000000003,41.399999999999999,45.799999999999997,42.899999999999999,28.399999999999999,25.899999999999999,27.899999999999999,27.399999999999999,15.800000000000001,13.800000000000001,15.800000000000001,16.100000000000001,19.5,17.699999999999999,18.600000000000001,17.699999999999999,34.299999999999997,33.899999999999999,36.899999999999999,34.399999999999999,33.700000000000003,34.899999999999999,35,33.100000000000001,46,48.799999999999997,58,52.799999999999997,32.899999999999999,34.100000000000001,34.899999999999999,33,21.699999999999999,22.600000000000001,23.800000000000001,24.699999999999999,27.399999999999999,30.300000000000001,32.200000000000003,29.600000000000001,23.600000000000001,21.600000000000001,28.699999999999999,26.100000000000001,26.399999999999999,27.800000000000001,26.100000000000001,23.5,22.699999999999999,21.699999999999999,22.100000000000001,20.600000000000001,22.399999999999999,21.300000000000001,26.600000000000001,24.600000000000001,13.9,13.699999999999999,14,13.6,37.899999999999999,36.899999999999999,37.5,36.700000000000003,33.799999999999997,37.600000000000001,39.700000000000003,32.799999999999997,34.899999999999999,33.600000000000001,38,34.200000000000003,37.899999999999999,37.899999999999999,38.200000000000003,36,35.600000000000001,37.200000000000003,37,41,20.699999999999999,21.199999999999999,23.199999999999999,22.699999999999999,29.199999999999999,28.899999999999999,31.899999999999999,29.699999999999999,44.299999999999997,37.899999999999999,40.399999999999999,40.899999999999999,36.299999999999997,40.5,39.700000000000003,35.600000000000001,45,41.100000000000001,44.399999999999999,37.700000000000003,38.399999999999999,38.600000000000001,44.600000000000001,41.899999999999999,42.100000000000001,39,42.899999999999999,40.700000000000003,37.700000000000003,35.100000000000001,31,38.799999999999997,27.100000000000001,26.899999999999999,28.699999999999999,27.5,45.200000000000003,42.200000000000003,42.899999999999999,45.5,31,32.299999999999997,35.899999999999999,35.399999999999999,31.699999999999999,30.5,33.200000000000003,33,41.5,34.399999999999999,32.100000000000001,32.700000000000003],"nbinsx":30,"marker":{"color":"rgba(55, 128, 191, 0.7)","line":{"color":"rgba(55, 128, 191, 0.7)","width":2}},"type":"histogram","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Since our goal is to create a model to predict the death rate, we
separately examine the distribution of predictor variables. As shown in
the above chart, the distribution of death rate is almost symmetric,
thus we do not perform any transformations on it for now.</p>
<pre class="r"><code>test = data |&gt;
  drop_na(death_rate)

mean(test$death_rate) - median(test$death_rate)</code></pre>
<pre><code>## [1] -0.6235</code></pre>
</div>
<div id="multi-colinearity-check" class="section level3">
<h3>Multi-colinearity Check</h3>
<p>Due to multicollinearity potentially leading to substantial
fluctuations in coefficient estimates and reduced precision of the
estimates, we grouped predictor variables with similar properties or
correlations to examine multicollinearity. We divided <code>gdp</code>,
<code>pce</code>, <code>rpp</code>, <code>employment_rate</code>,
<code>hc_exp</code>, <code>income</code>, and <code>edu_level</code>
into one group representing economic and social factors, and
<code>diabetes_rate</code>, <code>cardio_rate</code>,
<code>smoke_rate</code>, <code>elder_rate</code>, and
<code>obesity_rate</code> into another group representing health and
disease-related factors for analysis. Correlation heatmaps can help us
identify whether there is multicollinearity among the selected predictor
variables.</p>
<pre class="r"><code># Handling missing data, here we choose to delete rows containing missing values.
data &lt;- na.omit(data)</code></pre>
<pre class="r"><code>library(corrplot)
data_selected_social &lt;- data %&gt;% select(gdp, pce, rpp, employment,hc_exp,income,edu_level)
# Calculate the correlation matrix
correlation_matrix &lt;- cor(data_selected_social)

# Visualize the correlation matrix
corrplot(correlation_matrix, type = &quot;upper&quot;, order = &quot;hclust&quot;, tl.col = &quot;black&quot;, tl.srt = 45)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-12-1.png" width="90%" /></p>
<p>From the heatmap, we observed a high degree of correlation among GDP,
personal consumption expenditure (PCE), regional price parity (RPP),
employment, healthcare expenditure (HC_EXP), income, and education
level. Consequently, we decided to remove GDP, PCE, and RPP from our
analysis. Firstly, from a practical standpoint, while GDP, PCE, and RPP
do provide some insights into the economic conditions of a region, their
direct connection to Alzheimer’s disease death rates may be relatively
weak. In contrast, variables like employment status, healthcare
expenditure, personal income, and education level are more likely to
directly impact the survival rates of Alzheimer’s disease patients.
Secondly, removing highly correlated variables helps mitigate the issues
related to multicollinearity, enhancing the stability and
interpretability of the model.</p>
<pre class="r"><code>data_selected_desease &lt;- data %&gt;% select(diabetes_rate,cardio_rate,smoke_rate,elder_rate,obesity_rate)
# Calculate the correlation matrix
correlation_matrix &lt;- cor(data_selected_desease)

# Visualize the correlation matrix
corrplot(correlation_matrix, type = &quot;upper&quot;, order = &quot;hclust&quot;, tl.col = &quot;black&quot;, tl.srt = 45)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-13-1.png" width="90%" /></p>
<p>Based on the heatmap, it can be observed that the variables
<code>diabetes_rate</code> and <code>obesity_rate</code> are highly
correlated. Among these variables, we ultimately chose to delete
diabetes_rate while retaining <code>cardio_rate</code>. Some studies
have indicated a certain association between heart disease and
Alzheimer’s disease. Heart disease may affect blood supply to the brain,
which is related to cognitive decline. Therefore, retaining the
<code>cardio_rate</code> as a predictive variable may help capture this
potential association.</p>
</div>
<div id="correlation-and-scatter-plot" class="section level3">
<h3>Correlation and Scatter Plot:</h3>
<pre class="r"><code>data |&gt;
  select(year, death_rate, smoke_rate, cardio_rate, obesity_rate, elder_rate) |&gt;
  pivot_longer(
    smoke_rate:elder_rate,
    names_to = &quot;category&quot;,
    values_to = &quot;Rate&quot;) |&gt;
  mutate(year = as.character(year),
         category = case_match(
           category,
           &quot;smoke_rate&quot; ~ &quot;Smoke Rate&quot;,
           &quot;cardio_rate&quot; ~ &quot;Cardiovascular Disease Rate&quot;,
           &quot;obesity_rate&quot; ~ &quot;Obesity Rate&quot;,
           &quot;elder_rate&quot; ~ &quot;Elder Rate&quot;
         )) |&gt;
  ggplot(aes(x = Rate, y = death_rate, color = year)) +
  geom_point(alpha = 0.5, size = 0.8) +
  geom_smooth(method = &#39;lm&#39;, se = TRUE, size = 0.5, color = &#39;red&#39;)  +
  theme_minimal() + 
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text = element_text(color = &quot;grey20&quot;),
    axis.title = element_text(color = &quot;grey20&quot;)
  ) +
  labs(
    title = &quot;Scatter Plot for Death Rate and Health Related Factors Across Years&quot;,
    y = &quot;Death Rate&quot;,
    color = &quot;Year&quot;
  ) +
  facet_wrap(~category, scales = &quot;free&quot;, ncol = 2)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-14-1.png" width="90%" /></p>
<p>There is a positive correlation between the proportion of smokers and
the prevalence of obesity and cardiovascular disease, and the overall
mortality rate. Conversely, the percentage of the population aged 65 and
older shows a negative correlation with the mortality rate. This
suggests that a higher percentage of older adults may reflect a more
advanced state of medical care in that region, potentially leading to a
lower rate of deaths attributed to Alzheimer’s disease</p>
<pre class="r"><code>data |&gt;
  select(year, death_rate, income, employment, hc_exp, rpp) |&gt;
  pivot_longer(
    income:rpp,
    names_to = &quot;category&quot;,
    values_to = &quot;Value&quot;) |&gt;
  mutate(year = as.character(year),
         category = case_match(
           category,
           &quot;income&quot; ~ &quot;Income&quot;,
           &quot;employment&quot; ~ &quot;Empoyment Rate&quot;,
           &quot;hc_exp&quot; ~ &quot;Healthcare Expenditure&quot;,
           &quot;rpp&quot; ~ &quot;Regional price parities&quot;
         )) |&gt;
  ggplot(aes(x = Value, y = death_rate, color = year)) +
  geom_point(alpha = 0.5, size = 0.8) +
  geom_smooth(method = &#39;lm&#39;, se = TRUE, size = 0.5, color = &#39;red&#39;)  +
  theme_minimal() + 
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text = element_text(color = &quot;grey20&quot;),
    axis.title = element_text(color = &quot;grey20&quot;)
  ) +
  labs(
    title = &quot;Scatter Plot for Death Rate and Social Related Factors Across Years&quot;,
    y = &quot;Death Rate&quot;,
    color = &quot;Year&quot;
  ) +
  facet_wrap(~category, scales = &quot;free&quot;, ncol = 2)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-15-1.png" width="90%" /></p>
<p>There are negative association between Alzheimer’s disease mortality
rates and factors such as income, employment, price index, and
healthcare expenditure. Higher income and employment levels, often
associated with better access to healthcare, correspond with lower
Alzheimer’s death rates. Similarly, regions with a higher price index
and greater healthcare spending show fewer deaths from this disease.</p>
<p>However, the data points show a lack of tight clustering, which
suggests that a linear model might not fully capture the nuances of
these relationships. This pattern hints at the potential for a more
complex, non-linear relationship between these socio-economic factors
and Alzheimer’s mortality.</p>
<pre class="r"><code>data |&gt;
  ggplot(aes(x = edu_level, y = death_rate, color = as.factor(year))) + 
  geom_point(alpha = 0.5, size = 0.8) +
  geom_smooth(method = &#39;lm&#39;, se = TRUE, size = 0.8, color = &#39;red&#39;) +
  labs(
    title = &quot;Scatter Plot for Death Rate and Education Level Across Years&quot;,
    x = &quot;Educational Level&quot;,
    y = &quot;Death Rate&quot;,
    color = &quot;Year&quot;
  ) +
  theme_minimal() + 
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text = element_text(color = &quot;grey20&quot;),
    axis.title = element_text(color = &quot;grey20&quot;)
  )</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-16-1.png" width="90%" /></p>
<p>The graph illustrates a trend where higher levels of educational
attainment are associated with lower mortality rates. This pattern
suggests that better education may contribute to improved health
outcomes, potentially due to increased health awareness, better access
to healthcare resources, or healthier lifestyle choices typically
associated with higher education levels.</p>
<p>However, it’s important to consider that Alzheimer’s disease
predominantly affects older individuals, and there may be a temporal
discrepancy between the current education levels and those of the older
population primarily impacted by this disease. This time-related
difference suggests that while educational attainment appears to be a
protective factor, the actual impact on Alzheimer’s mortality might be
influenced by historical changes in education over the decades.
Therefore, when interpreting these results, we should be cautious about
directly correlating current educational standards with Alzheimer’s
outcomes in an aging population.</p>
</div>
</div>
<div id="preliminary-analysis" class="section level2">
<h2>Preliminary Analysis</h2>
<div id="death-rate-by-regions" class="section level3">
<h3>1. Death rate by Regions</h3>
<pre class="r"><code>data &lt;- read_csv(&quot;data/geo_data.csv&quot;) |&gt; 
  mutate(region = case_when(
    state %in% c(&quot;Connecticut&quot;, &quot;Maine&quot;, &quot;Massachusetts&quot;, &quot;New Hampshire&quot;, &quot;New Jersey&quot;, &quot;New York&quot;, &quot;Pennsylvania&quot;, &quot;Rhode Island&quot;, &quot;Vermont&quot;) ~ &quot;Northeast&quot;,
    state %in% c(&quot;Illinois&quot;, &quot;Indiana&quot;, &quot;Iowa&quot;, &quot;Kansas&quot;, &quot;Michigan&quot;, &quot;Minnesota&quot;, &quot;Missouri&quot;, &quot;Nebraska&quot;, &quot;North Dakota&quot;, &quot;Ohio&quot;, &quot;South Dakota&quot;, &quot;Wisconsin&quot;) ~ &quot;Midwest&quot;,
    state %in% c(&quot;Alabama&quot;, &quot;Arkansas&quot;, &quot;Delaware&quot;, &quot;District of Columbia&quot;, &quot;Florida&quot;, &quot;Georgia&quot;, &quot;Kentucky&quot;, &quot;Louisiana&quot;, &quot;Maryland&quot;, &quot;Mississippi&quot;, &quot;North Carolina&quot;, &quot;Oklahoma&quot;, &quot;South Carolina&quot;, &quot;Tennessee&quot;, &quot;Texas&quot;, &quot;Virginia&quot;, &quot;West Virginia&quot;) ~ &quot;South&quot;,
    state %in% c(&quot;Alaska&quot;, &quot;Arizona&quot;, &quot;California&quot;, &quot;Colorado&quot;, &quot;Hawaii&quot;, &quot;Idaho&quot;, &quot;Montana&quot;, &quot;Nevada&quot;, &quot;New Mexico&quot;, &quot;Oregon&quot;, &quot;Utah&quot;, &quot;Washington&quot;, &quot;Wyoming&quot;) ~ &quot;West&quot;
  ))</code></pre>
<pre class="r"><code>data |&gt; 
  janitor::clean_names() |&gt; 
  group_by(region) |&gt; 
  summarise(avg_death_rate = mean(death_rate, na.rm = TRUE)) |&gt; 
  arrange(avg_death_rate) |&gt; 
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">region</th>
<th align="right">avg_death_rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Northeast</td>
<td align="right">23.817</td>
</tr>
<tr class="even">
<td align="left">West</td>
<td align="right">32.160</td>
</tr>
<tr class="odd">
<td align="left">Midwest</td>
<td align="right">32.171</td>
</tr>
<tr class="even">
<td align="left">South</td>
<td align="right">36.584</td>
</tr>
</tbody>
</table>
<ul>
<li><p>The boxplot displays the distribution of Alzheimer’s Disease
death rates across different regions.</p></li>
<li><p>While the boxplot primarily illustrates the interquartile range
and median, it provides a visual representation of the spread of death
rates within each region. In particular, the length of the box and the
positioning of the median line indicate the central tendency, and the
whiskers show the range of data.</p></li>
<li><p>Notably, the South region exhibits a wider spread of death rates,
suggesting greater variability in Alzheimer’s Disease mortality within
this region compared to others.</p></li>
<li><p>The observation of varying spreads among regions implies
potential heterogeneity in Alzheimer’s Disease death rates, indicating
the importance of further investigation into the factors contributing to
this variability.</p></li>
</ul>
<pre class="r"><code>data  |&gt; 
  janitor::clean_names()  |&gt; 
  group_by(region)  |&gt; 
  ggplot(aes(x = fct_reorder(region, death_rate), y = death_rate, fill = region)) +
  geom_boxplot() +
  labs(title = &quot;Boxplot of Death Rate by Regions&quot;, x = &quot;Region&quot;, y = &quot;Death Rate&quot;) +
  theme(axis.text.x = element_text(hjust = 1, angle = 10, size = 8))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-19-1.png" width="90%" /></p>
<ul>
<li><p>The boxplot shows the distribution of death rate in each
region.</p></li>
<li><p>The variance of death rate is higher in South region.</p></li>
<li><p>We can roughly tell from the plot that the variances of death
rate among regions are not equal. Thus, we may perform a statistical
test to check heteroscedasticity</p></li>
</ul>
<div id="test-of-equal-variances" class="section level4">
<h4>Test of equal variances</h4>
<center>
<em>H<sub>0</sub> : Equal variance among regions vs H<sub>1</sub> :
Unequal variance</em>
<center>
<pre class="r"><code>bartlett.test(death_rate ~ factor(region), data = data) |&gt; 
  broom::tidy() |&gt; 
  knitr::kable()</code></pre>
<table>
<colgroup>
<col width="14%" />
<col width="11%" />
<col width="14%" />
<col width="60%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="left">method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">31.09801</td>
<td align="right">8e-07</td>
<td align="right">3</td>
<td align="left">Bartlett test of homogeneity of variances</td>
</tr>
</tbody>
</table>
<p>Based on the less-than-significance level of the p-value (usually
0.05), we have enough evidence to reject the null hypothesis of variance
homogeneity. Therefore, we can assume that the variance of mortality
rates is not equal under different regions. This may have important
implications for some statistical methods (e.g., analysis of variance
ANOVA), which typically assume variance chi-square.</p>
</div>
<div
id="t.test-compare-mean-death-rate-between-west-america-and-midwest-america"
class="section level4">
<h4>t.test : Compare Mean Death Rate Between West America and Midwest
America</h4>
<p>From the boxplot above, we find that the Alzheimer’s Disease death
rate in West region and Midwest region are almost overlapping. Though
the median of Midwest region is higher, the variance in West region
seems smaller. Thus, we want to study if the mean death rate in the two
regions are significantly different.</p>
<div id="extract-death-rate-in-west-america-and-midwest-america"
class="section level5">
<h5>Extract death rate in West America and Midwest America</h5>
<pre class="r"><code>west_death_rate &lt;- data |&gt; 
  filter(region == &quot;West&quot;) |&gt; 
  pull(death_rate)

midwest_death_rate &lt;- data |&gt;  
  janitor::clean_names() |&gt; 
  filter(region == &quot;Midwest&quot;) |&gt; 
  pull(death_rate)</code></pre>
<pre class="r"><code>var.test(west_death_rate,midwest_death_rate,alternative = &quot;two.sided&quot;,conf.level = 0.95) |&gt;  
  broom::tidy() |&gt; 
  knitr::kable()</code></pre>
<table>
<colgroup>
<col width="8%" />
<col width="6%" />
<col width="6%" />
<col width="9%" />
<col width="9%" />
<col width="8%" />
<col width="9%" />
<col width="30%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">estimate</th>
<th align="right">num.df</th>
<th align="right">den.df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="left">method</th>
<th align="left">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2.968585</td>
<td align="right">51</td>
<td align="right">47</td>
<td align="right">2.968585</td>
<td align="right">0.0002431</td>
<td align="right">1.678201</td>
<td align="right">5.216459</td>
<td align="left">F test to compare two variances</td>
<td align="left">two.sided</td>
</tr>
</tbody>
</table>
<p>The null hypothesis for the variance test is that the two variance
are equal. The result shows that the p-value is much less than 0.05.
Thus, we may reject the null hypothesis and conclude that the variances
are not equal. Next, we should perform 2 sample t.test with unknown and
unequal variance.</p>
</div>
<div id="two-sample-t.test-with-unknown-unequal-variances"
class="section level5">
<h5>Two sample t.test with unknown unequal variances</h5>
<pre class="r"><code>t.test(west_death_rate,midwest_death_rate,alternative = &quot;less&quot;,conf.level = 0.95,paired = F,var.equal = FALSE ) |&gt; 
  broom::tidy() |&gt; 
  knitr::kable()</code></pre>
<table style="width:100%;">
<colgroup>
<col width="9%" />
<col width="8%" />
<col width="8%" />
<col width="9%" />
<col width="8%" />
<col width="8%" />
<col width="7%" />
<col width="8%" />
<col width="20%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">estimate</th>
<th align="right">estimate1</th>
<th align="right">estimate2</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="left">method</th>
<th align="left">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-0.0112179</td>
<td align="right">32.15962</td>
<td align="right">32.17083</td>
<td align="right">-0.0091864</td>
<td align="right">0.4963462</td>
<td align="right">83.01814</td>
<td align="right">-Inf</td>
<td align="right">2.020069</td>
<td align="left">Welch Two Sample t-test</td>
<td align="left">less</td>
</tr>
</tbody>
</table>
<ul>
<li>The p-value is greater than the conventional significance level of
0.05, suggesting that there is not enough evidence to reject the null
hypothesis. The results indicate that, based on the data, there is no
significant difference in death rates between the “west” and “midwest”
regions, or the death rate in the “west” region is not significantly
less than the death rate in the “midwest” region.</li>
</ul>
</div>
</div>
</div>
<div
id="average-alzheimers-disease-death-rate-by-region-year-combination"
class="section level3">
<h3>2. Average Alzheimer’s Disease death rate by (region, year)
Combination</h3>
<pre class="r"><code>data |&gt;  
  group_by(region,year) |&gt; 
  summarise(avg_by_year_region = mean(death_rate,na.rm = T)) |&gt; 
  pivot_wider(
    names_from = region,
    values_from = avg_by_year_region
  ) |&gt;  
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">year</th>
<th align="right">Midwest</th>
<th align="right">Northeast</th>
<th align="right">South</th>
<th align="right">West</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2018</td>
<td align="right">31.583</td>
<td align="right">24.111</td>
<td align="right">36.269</td>
<td align="right">31.885</td>
</tr>
<tr class="even">
<td align="right">2019</td>
<td align="right">31.883</td>
<td align="right">23.344</td>
<td align="right">34.869</td>
<td align="right">30.662</td>
</tr>
<tr class="odd">
<td align="right">2020</td>
<td align="right">34.150</td>
<td align="right">23.900</td>
<td align="right">38.675</td>
<td align="right">33.115</td>
</tr>
<tr class="even">
<td align="right">2021</td>
<td align="right">31.067</td>
<td align="right">23.911</td>
<td align="right">36.525</td>
<td align="right">32.977</td>
</tr>
</tbody>
</table>
<pre class="r"><code>data |&gt;  
  group_by(region,year) |&gt; 
  summarise(avg_by_year_region = mean(death_rate,na.rm = T)) %&gt;% 
  ggplot(aes(x = year, y = avg_by_year_region, color = region)) +
  geom_line() + 
  geom_point() + 
  labs(
    y = &quot;Average Alzheimer&#39;s Disease death rate&quot;,
    title = &quot;Average Alzheimer&#39;s Disease death rate by Region, Year&quot;) </code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-25-1.png" width="90%" /></p>
<ul>
<li><p>The table and line graph above show the descriptive statistics
and overall trend.</p></li>
<li><p>It is clearly shown in the plot that Northeast region has a much
lower and South resgion has a much higher average Alzheimer’s Disease
death rate than the other regions.</p></li>
</ul>
</div>
<div id="average-alzheimers-disease-death-rate-by-income-level"
class="section level3">
<h3>3. Average Alzheimer’s Disease death rate by Income Level</h3>
<pre class="r"><code>  data |&gt; 
  group_by(year) |&gt; 
  select(year,income) |&gt; 
  summarise(median_income_by_year = median(income,na.rm = T)) |&gt; 
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">year</th>
<th align="right">median_income_by_year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2018</td>
<td align="right">48986.21</td>
</tr>
<tr class="even">
<td align="right">2019</td>
<td align="right">49792.03</td>
</tr>
<tr class="odd">
<td align="right">2020</td>
<td align="right">52442.06</td>
</tr>
<tr class="even">
<td align="right">2021</td>
<td align="right">54057.93</td>
</tr>
</tbody>
</table>
<ul>
<li><p>The table above shows the median personal annual income of each
year.</p></li>
<li><p>Then, we use the median personal annual income of each year to
categorize different income groups (with”less than median income” as
“Lower Income”, “more than 1.3 times of median income” as “Upper
Income”, and those between these ranges as “Middle Income”.</p></li>
<li><p>We use this income group division to calculate average
Alzheimer’s Disease death rate of each group.</p></li>
</ul>
<pre class="r"><code>income_level_2018 =
  data |&gt;  
  group_by(year) |&gt; 
  filter(year == 2018) |&gt; 
  mutate(
    income_group = case_when(
      income &lt; 48986.21 ~&quot;Lower Income&quot;,
      income &gt; 1.3* 48986.21 ~&quot;Upper Income&quot;,
      TRUE ~  &quot;Middle income&quot;
    )) 

income_level_2019 =
  data |&gt;  
  group_by(year) |&gt; 
  filter(year == 2019) |&gt; 
  mutate(
    income_group = case_when(
      income &lt;49792.03 ~&quot;Lower Income&quot;,
      income &gt; 1.3* 49792.03 ~&quot;Upper Income&quot;,
      TRUE ~  &quot;Middle income&quot;
    ))

income_level_2020 =
  data |&gt;  
  group_by(year) |&gt; 
  filter(year == 2020) |&gt; 
  mutate(
    income_group = case_when(
      income &lt;52442.06 ~&quot;Lower Income&quot;,
      income &gt; 1.3* 52442.06 ~&quot;Upper Income&quot;,
      TRUE ~  &quot;Middle income&quot;
    )) 
    
income_level_2021 =
  data |&gt;  
  group_by(year) |&gt; 
  filter(year == 2021) |&gt; 
  mutate(
    income_group = case_when(
      income &lt;54057.93 ~&quot;Lower Income&quot;,
      income &gt; 1.3* 54057.93 ~&quot;Upper Income&quot;,
      TRUE ~  &quot;Middle income&quot;
    ))

income_level =
  bind_rows(income_level_2018,income_level_2019,income_level_2020,income_level_2021)

income_level |&gt; 
  filter(!is.na(income_group)) |&gt;  
  group_by(income_group) |&gt; 
  summarise(avg_by_income = mean(death_rate,na.rm = T)) |&gt;  
  arrange(avg_by_income) |&gt; 
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">income_group</th>
<th align="right">avg_by_income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Upper Income</td>
<td align="right">18.300</td>
</tr>
<tr class="even">
<td align="left">Middle income</td>
<td align="right">28.971</td>
</tr>
<tr class="odd">
<td align="left">Lower Income</td>
<td align="right">35.270</td>
</tr>
</tbody>
</table>
<pre class="r"><code>income_level |&gt; 
  filter(!is.na(income_group)) |&gt;  
  group_by(income_group) |&gt; 
  filter(!is.na(death_rate)) |&gt; 
  ggplot(aes(x = fct_reorder(income_group,death_rate), y = death_rate,fill = income_group)) +
  geom_boxplot() +
  labs(
  title = &quot;Boxplot of Alzheimer&#39;s Disease Death Rate by Income Groups&quot;, 
  x = &quot;Income Groups&quot;,
  y = &quot;Alzheimer&#39;s Disease death rate&quot;)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-28-1.png" width="90%" /></p>
<ul>
<li><p>The boxes of different income groups are almost not overlapping
with each other.</p></li>
<li><p>The pattern is clear that people from lower income group tend to
have a higher Alzheimer’s Disease Death Rate.</p></li>
</ul>
<center>
<em>H<sub>0</sub> : mean of death_rate are equal in three groups vs
H<sub>1</sub> : at least two means are not equal</em>
</center>
<pre class="r"><code>anova_result &lt;- aov(death_rate ~ factor(income_group), data = income_level)

TukeyHSD(anova_result) |&gt; 
  broom::tidy() |&gt; 
  knitr::kable()</code></pre>
<table style="width:100%;">
<colgroup>
<col width="20%" />
<col width="26%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="9%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="left">contrast</th>
<th align="right">null.value</th>
<th align="right">estimate</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="right">adj.p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">factor(income_group)</td>
<td align="left">Middle income-Lower Income</td>
<td align="right">0</td>
<td align="right">-6.298775</td>
<td align="right">-8.991971</td>
<td align="right">-3.605578</td>
<td align="right">0.0000003</td>
</tr>
<tr class="even">
<td align="left">factor(income_group)</td>
<td align="left">Upper Income-Lower Income</td>
<td align="right">0</td>
<td align="right">-16.969608</td>
<td align="right">-30.492597</td>
<td align="right">-3.446618</td>
<td align="right">0.0095320</td>
</tr>
<tr class="odd">
<td align="left">factor(income_group)</td>
<td align="left">Upper Income-Middle income</td>
<td align="right">0</td>
<td align="right">-10.670833</td>
<td align="right">-24.201947</td>
<td align="right">2.860281</td>
<td align="right">0.1524562</td>
</tr>
</tbody>
</table>
<ul>
<li><p>The ANOVA results indicate a significant difference in mean life
expectancy among different income groups (p &lt; 0.05). The post hoc
tests further reveal:</p></li>
<li><p>A significant difference in mean life expectancy between Middle
Income and Lower Income groups.</p></li>
<li><p>A significant difference in mean life expectancy between Upper
Income and Lower Income groups.</p></li>
<li><p>No significant difference in mean life expectancy between Upper
Income and Middle Income groups.</p></li>
</ul>
<p>In summary, there are statistically significant variations in life
expectancy across income groups, with specific differences observed in
pairwise comparisons between Middle Income vs. Lower Income and Upper
Income vs. Lower Income.</p>
</div>
<div id="average-alzheimers-disease-death-rate-by-employment"
class="section level3">
<h3>4. Average Alzheimer’s Disease death rate by Employment</h3>
<pre class="r"><code>  data |&gt; 
  group_by(year) |&gt; 
  select(year,employment) |&gt; 
  summarise(med_employ_by_year = median(employment,na.rm = T)) |&gt; 
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">year</th>
<th align="right">med_employ_by_year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2018</td>
<td align="right">0.617</td>
</tr>
<tr class="even">
<td align="right">2019</td>
<td align="right">0.617</td>
</tr>
<tr class="odd">
<td align="right">2020</td>
<td align="right">0.588</td>
</tr>
<tr class="even">
<td align="right">2021</td>
<td align="right">0.612</td>
</tr>
</tbody>
</table>
<ul>
<li><p>The table above shows the median personal annual income of each
year.</p></li>
<li><p>Then, we use the median employment rate of each year to
categorize different employment groups (with”less than or equal to
median” as “Lower Employment Rate”, “more than median” as “High
Employment Rate”.</p></li>
<li><p>We use this employment group division to calculate average
Alzheimer’s Disease death rate of each group.</p></li>
</ul>
<pre class="r"><code>employ_2018 =
  data |&gt;  
  group_by(year) |&gt; 
  filter(year == 2018) |&gt; 
  mutate(
    employ_group = case_when(
      employment &lt;= 0.617 ~&quot;Low Employment Rate&quot;,
      employment &gt;0.617~&quot;High Employment Rate&quot;,
    )) 
  
employ_2019 =
  data |&gt;  
  group_by(year) |&gt; 
  filter(year == 2019) |&gt; 
  mutate(
    employ_group = case_when(
      employment &lt;= 0.617 ~&quot;Low Employment Rate&quot;,
      employment &gt; 0.617~&quot;High Employment Rate&quot;,
    )) 

employ_2020 =
  data |&gt;  
  group_by(year) |&gt; 
  filter(year == 2020) |&gt; 
  mutate(
    employ_group = case_when(
      employment &lt;= 0.588 ~&quot;Low Employment Rate&quot;,
      employment &gt; 0.588~&quot;High Employment Rate&quot;,
    )) 
    
employ_2021 =
  data |&gt;  
  group_by(year) |&gt; 
  filter(year == 2021) |&gt; 
  mutate(
    employ_group = case_when(
      employment &lt;= 0.612 ~&quot;Low Employment Rate&quot;,
      employment &gt;0.612~&quot;High Employment Rate&quot;,
    )) 

employ_level =
  bind_rows(employ_2018,employ_2019,employ_2020,employ_2021)

employ_level |&gt; 
  group_by(employ_group) |&gt; 
  summarise(avg_by_employ = mean(death_rate,na.rm = T)) |&gt;  
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">employ_group</th>
<th align="right">avg_by_employ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">High Employment Rate</td>
<td align="right">29.345</td>
</tr>
<tr class="even">
<td align="left">Low Employment Rate</td>
<td align="right">34.701</td>
</tr>
</tbody>
</table>
<pre class="r"><code>employ_level |&gt; 
  group_by(employ_group) |&gt; 
  ggplot(aes(x = employ_group, y = death_rate,fill = employ_group)) +
  geom_boxplot() +
  labs(
  title = &quot;Boxplot of Alzheimer&#39;s Disease Death Rate by Employment Rate&quot;,
  x = &quot;Employment Rate&quot;,
  y = &quot;Alzheimer&#39;s Disease Death Rate&quot;)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-32-1.png" width="90%" /></p>
<ul>
<li>The pattern is clear that low employment tend to a higher
Alzheimer’s Disease death rate.</li>
</ul>
<center>
<em>H<sub>0</sub> : mean high employment = mean low employment vs
H<sub>1</sub> : mean high employment ≠ mean low employment</em>
</center>
<pre class="r"><code>t.test(death_rate ~ factor(employ_group),data = employ_level, alternative = &quot;less&quot;,conf.level = 0.95,paired = F,var.equal = TRUE ) |&gt;  
  broom::tidy() |&gt; 
  knitr::kable()</code></pre>
<table>
<colgroup>
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="7%" />
<col width="9%" />
<col width="8%" />
<col width="9%" />
<col width="16%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">estimate</th>
<th align="right">estimate1</th>
<th align="right">estimate2</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="left">method</th>
<th align="left">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-5.356082</td>
<td align="right">29.3449</td>
<td align="right">34.70098</td>
<td align="right">-4.571787</td>
<td align="right">4.3e-06</td>
<td align="right">198</td>
<td align="right">-Inf</td>
<td align="right">-3.419994</td>
<td align="left">Two Sample t-test</td>
<td align="left">less</td>
</tr>
</tbody>
</table>
<ul>
<li>We have also performed 2 sample t.test to compare the mean death
rate between the two groups. We conclude that the means are not equal.
Since the method is similar to what we have used and displayed when
studying the regional differences, we do not show the process here.</li>
</ul>
</div>
<div id="summary" class="section level3">
<h3>Summary</h3>
<p>In this analysis, we explored the impact of various factors on
Alzheimer’s Disease death rates using statistical tests and
visualizations. Key findings include:</p>
<ul>
<li><p>Regional differences in Alzheimer’s Disease death rates, with the
South region having the highest and the Northeast region having the
lowest average death rates.</p></li>
<li><p>Significant variations in Alzheimer’s Disease death rates based
on income and employment groups, indicating that socioeconomic factors
play a role in disease outcomes.</p></li>
</ul>
</div>
</div>
</div>
<div id="model" class="section level1">
<h1>Model</h1>
<div id="data-set-splitting" class="section level2">
<h2>Data Set Splitting</h2>
<p>We used data from the years 2018 to 2020 to train our models, and
data from 2021 to perform prediction.</p>
<p>All these datasets have been filtered to remove any missing values
and do not contain any outliers, ensuring that the data quality is high.
This preprocessing step lays a strong foundation for building accurate
and reliable models.</p>
<pre class="r"><code>data = readRDS(&quot;data_for_model.rds&quot;) 
training_data = filter(data, year &gt;= 2018 &amp; year &lt;= 2020) |&gt;
  select(-c(state,year))

testing_data = filter(data, year == 2021) |&gt;
  select(-c(state,year))</code></pre>
</div>
<div id="multiple-linear-regression" class="section level2">
<h2>Multiple Linear Regression</h2>
<div id="model-selection" class="section level3">
<h3>Model Selection</h3>
<p>The reason for initially choosing linear models in statistical
analysis is their simplicity and ease of understanding. These models, by
representing relationships in a straightforward linear manner, make it
easier for us to comprehend how different variables affect the death
rate we care about.</p>
<p>Moreover, linear models are known for their robustness, offering
reliable performance even with various types of data and statistical
errors. Importantly, they serve as an effective benchmark in more
complex modeling processes.</p>
<p>By starting with a linear model, we can establish a baseline
performance level, against which the effectiveness of more sophisticated
models can be measured. This stepwise approach helps in ensuring that
the complexity of a model is justified by a significant improvement over
the simpler linear model.</p>
<div id="full-model-linear-regression" class="section level4">
<h4>Full model: Linear regression</h4>
<pre class="r"><code>model = lm(death_rate ~ employment + hc_exp + income + edu_level + cardio_rate + smoke_rate + elder_rate, data = training_data)
summary(model) |&gt; 
broom::tidy() |&gt;
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">68.3037142</td>
<td align="right">13.4233735</td>
<td align="right">5.0884164</td>
<td align="right">0.0000012</td>
</tr>
<tr class="even">
<td align="left">employment</td>
<td align="right">24.9223618</td>
<td align="right">16.5331015</td>
<td align="right">1.5074221</td>
<td align="right">0.1340921</td>
</tr>
<tr class="odd">
<td align="left">hc_exp</td>
<td align="right">-0.0012826</td>
<td align="right">0.0007332</td>
<td align="right">-1.7492692</td>
<td align="right">0.0825687</td>
</tr>
<tr class="even">
<td align="left">income</td>
<td align="right">-0.0002319</td>
<td align="right">0.0001776</td>
<td align="right">-1.3061814</td>
<td align="right">0.1937624</td>
</tr>
<tr class="odd">
<td align="left">edu_level</td>
<td align="right">-45.7011712</td>
<td align="right">21.4826355</td>
<td align="right">-2.1273540</td>
<td align="right">0.0352503</td>
</tr>
<tr class="even">
<td align="left">cardio_rate</td>
<td align="right">180.2845378</td>
<td align="right">51.4160324</td>
<td align="right">3.5063876</td>
<td align="right">0.0006212</td>
</tr>
<tr class="odd">
<td align="left">smoke_rate</td>
<td align="right">-11.4113239</td>
<td align="right">31.4644509</td>
<td align="right">-0.3626735</td>
<td align="right">0.7174288</td>
</tr>
<tr class="even">
<td align="left">elder_rate</td>
<td align="right">-152.9455140</td>
<td align="right">35.4789569</td>
<td align="right">-4.3108797</td>
<td align="right">0.0000316</td>
</tr>
</tbody>
</table>
<pre class="r"><code>broom::glance(model) |&gt;
  mutate(model = &quot;Full Linear Regression&quot;) |&gt;
  select(model, r.squared, adj.r.squared, p.value, AIC, BIC) |&gt;
  knitr::kable()</code></pre>
<table>
<colgroup>
<col width="31%" />
<col width="13%" />
<col width="19%" />
<col width="10%" />
<col width="12%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">model</th>
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">p.value</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Full Linear Regression</td>
<td align="right">0.3990315</td>
<td align="right">0.367162</td>
<td align="right">0</td>
<td align="right">956.2865</td>
<td align="right">982.7613</td>
</tr>
</tbody>
</table>
<p>Based on the table of full model, some of the predictors are
statistically significant while others are not, so we need a further
selection of the model.</p>
</div>
<div id="backwards-elimination" class="section level4">
<h4>Backwards Elimination</h4>
<p>We use Backward Elimination for constructing our linear regression
model to enhance its efficiency and interpretability. This method
systematically removes the least significant variables, ensuring that
only the most impactful predictors are retained. Consequently, it helps
in reducing model complexity and avoiding overfitting, resulting in a
more robust and meaningful model.</p>
<pre class="r"><code>backward_result = step(model, direction = &#39;backward&#39;, trace = 0)
  broom::tidy(backward_result) |&gt;
      knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">74.2170216</td>
<td align="right">7.6615066</td>
<td align="right">9.687001</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">hc_exp</td>
<td align="right">-0.0014021</td>
<td align="right">0.0005712</td>
<td align="right">-2.454649</td>
<td align="right">0.0153748</td>
</tr>
<tr class="odd">
<td align="left">edu_level</td>
<td align="right">-47.8686408</td>
<td align="right">12.8765984</td>
<td align="right">-3.717491</td>
<td align="right">0.0002939</td>
</tr>
<tr class="even">
<td align="left">cardio_rate</td>
<td align="right">146.1913832</td>
<td align="right">46.7572070</td>
<td align="right">3.126606</td>
<td align="right">0.0021660</td>
</tr>
<tr class="odd">
<td align="left">elder_rate</td>
<td align="right">-155.1015760</td>
<td align="right">33.8923959</td>
<td align="right">-4.576294</td>
<td align="right">0.0000106</td>
</tr>
</tbody>
</table>
<pre class="r"><code>selected_model = lm(death_rate ~ hc_exp + edu_level + cardio_rate + elder_rate, data = training_data)

summary(selected_model) |&gt;
  broom::tidy() |&gt;
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">74.2170216</td>
<td align="right">7.6615066</td>
<td align="right">9.687001</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">hc_exp</td>
<td align="right">-0.0014021</td>
<td align="right">0.0005712</td>
<td align="right">-2.454649</td>
<td align="right">0.0153748</td>
</tr>
<tr class="odd">
<td align="left">edu_level</td>
<td align="right">-47.8686408</td>
<td align="right">12.8765984</td>
<td align="right">-3.717491</td>
<td align="right">0.0002939</td>
</tr>
<tr class="even">
<td align="left">cardio_rate</td>
<td align="right">146.1913832</td>
<td align="right">46.7572070</td>
<td align="right">3.126606</td>
<td align="right">0.0021660</td>
</tr>
<tr class="odd">
<td align="left">elder_rate</td>
<td align="right">-155.1015760</td>
<td align="right">33.8923959</td>
<td align="right">-4.576294</td>
<td align="right">0.0000106</td>
</tr>
</tbody>
</table>
<p>After applying Backward Elimination, we have obtained a linear
regression model that is streamlined and comprises only the
statistically significant predictors.</p>
</div>
</div>
<div id="model-performance" class="section level3">
<h3>Model Performance</h3>
<pre class="r"><code>pre =
  training_data |&gt;
  add_predictions(selected_model) |&gt;
  add_residuals(selected_model)

p1 &lt;- ggplot(pre, aes(x = pred, y = resid)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = &quot;dashed&quot;, color = &quot;red&quot;) +
  labs(
    x = &quot;Fitted Values&quot;,
    y = &quot;Residuals&quot;,
    title = &quot;Residuals vs Fitted Plot&quot;
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text = element_text(color = &quot;grey20&quot;),
    axis.title = element_text(color = &quot;grey20&quot;)
  )

residuals = resid(selected_model)
p2 &lt;- ggplot(as.data.frame(residuals), aes(sample = residuals)) +
  stat_qq() +
  stat_qq_line(color = &quot;red&quot;) +
  labs(
    title = &quot;Normal Q-Q Plot&quot;,
    x = &quot;Theoretical Quantiles&quot;,
    y = &quot;Sample Quantiles&quot;
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5)
  )

library(patchwork)
p1 + p2</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-38-1.png" width="90%" /></p>
<p>The residuals versus fitted plot shows a random distribution of
residuals around the zero line without any discernible patterns,
indicating good model fit and homoscedasticity. No obvious outliers are
present, suggesting that the linear regression model assumptions are
likely being met.</p>
<p>The QQ plot suggests although the slightly deviations at the tails
indicate potential non-normality, the residuals from a statistical model
are approximately normally distributed around the center.</p>
<pre class="r"><code>broom::glance(selected_model) |&gt;
  mutate(model = &quot;Selected Linear Regression&quot;) |&gt;
  select(model, r.squared, adj.r.squared, p.value, AIC, BIC) |&gt;
  knitr::kable()</code></pre>
<table>
<colgroup>
<col width="35%" />
<col width="12%" />
<col width="18%" />
<col width="10%" />
<col width="11%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">model</th>
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">p.value</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Selected Linear Regression</td>
<td align="right">0.3854173</td>
<td align="right">0.3672074</td>
<td align="right">0</td>
<td align="right">953.4226</td>
<td align="right">971.0725</td>
</tr>
</tbody>
</table>
<div id="cross-validation-for-rmse" class="section level4">
<h4>Cross Validation for RMSE</h4>
<p>To assess the performance and reliability of a predictive model, we
use the Cross-validation method to divide the training data into 100
subsets to ensure that each data point is used for both training and
testing. This helps assess how well the model generalizes to new, unseen
data.</p>
<pre class="r"><code># generate a cv dataframe 
cv_df =
  crossv_mc(training_data, 100) %&gt;% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
# fit the model to the generated CV dataframe
cv_df =
  cv_df |&gt;
  mutate(
    model  = map(train, ~lm(death_rate ~employment+hc_exp+income+edu_level+cardio_rate+smoke_rate+elder_rate, data = .x)),
    rmse = map2_dbl(model, test, ~rmse(model = .x, data = .y)))
# plot the prediction error
cv_df |&gt;
  select(rmse) |&gt;
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;) %&gt;% 
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin(fill = &quot;blue&quot;, alpha = 0.5) +
  labs(
    title = &quot;Prediction Errors For Our Model Under CV&quot;,
    x = &quot;Model Linear Regression&quot;,
    y = &quot;Prediction Errors&quot;
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text = element_text(color = &quot;grey20&quot;),
    axis.title = element_text(color = &quot;grey20&quot;)
  )</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-40-1.png" width="90%" /></p>
<p>The violin plot indicates a relatively concentrated distribution of
RMSE values for the linear regression model during cross-validation,
primarily within the 7 to 8 range, suggesting consistent prediction
errors without extreme variability. The symmetric shape around the
center suggests a median error likely within this range, implying a
stable model performance.</p>
</div>
<div id="bootstrap" class="section level4">
<h4>Bootstrap</h4>
<p>Bootstrapping, involving repeated sampling with replacement, ensures
that we are not just creating a model that works well for our current
dataset (as indicated by a high R²) but also one that is likely to
perform consistently across different, unseen datasets.</p>
<pre class="r"><code>training_data |&gt; 
  modelr::bootstrap(n = 1000) |&gt; 
  mutate(
    models = map(strap, \(df) lm(death_rate ~employment+hc_exp+income+edu_level+cardio_rate+smoke_rate+elder_rate, data = df)),
    results = map(models, broom::glance)) |&gt; 
  select(results) |&gt;
  unnest(results) |&gt;
  ggplot(aes(x = r.squared)) +
  geom_histogram(aes(y = ..density..), bins = 30, fill = &#39;blue&#39;, alpha = 0.5) +
  geom_density(alpha = .2, fill = &quot;red&quot;) +
  labs(title = &quot;Bootstrap Distribution of R²&quot;, x = &quot;R²&quot;, y = &quot;Density&quot;) +
  theme_minimal()</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-41-1.png" width="90%" /></p>
<p>Despite all the varibles are significant, R² value is around 0.4,
which is suggests potential nonlinear relationships or multicollinearity
issues in our dataset.</p>
</div>
</div>
</div>
<div id="random-forest-model" class="section level2">
<h2>Random Forest Model</h2>
<div id="model-selection-1" class="section level3">
<h3>Model Selection</h3>
<p>The Random Forest Model is an ensemble learning method, play an
important role in classification and regression tasks by building
multiple decision trees and aggregating their outputs. It handles
complex datasets well and is robust against overfitting. Thus, we
consider switching to Random Forest when linear models has limitations.
It effectively captures complex, non-linear relationships in data,
offering improved accuracy and deeper insights.</p>
<pre class="r"><code>library(randomForest)

rf_model &lt;- randomForest(death_rate ~  employment+hc_exp+income+edu_level+cardio_rate+smoke_rate+elder_rate, data = training_data)</code></pre>
</div>
<div id="model-performance-1" class="section level3">
<h3>Model Performance</h3>
<p>We also use cross validation and boostrap to see the performance and
reliability of the random forest model as we did to the linear
model.</p>
<div id="cross-validation-for-rmse-1" class="section level4">
<h4>Cross Validation for RMSE</h4>
<pre class="r"><code># generate a cv dataframe 
cv_df =
  crossv_mc(training_data, 100) %&gt;% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))

# fit the model to the generated CV dataframe
cv_df =
  cv_df |&gt; 
  mutate(
    model  = map(train, ~randomForest(death_rate ~employment+hc_exp+income+edu_level+cardio_rate+smoke_rate+elder_rate, data = .x)),
    rmse = map2_dbl(model, test, ~rmse(model = .x, data = .y)))

# plot the prediction error
cv_df |&gt;
  select(rmse) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;) %&gt;% 
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin(fill = &quot;blue&quot;, alpha = 0.5) +
  labs(
    title = &quot;Prediction Errors For Our Model Under CV&quot;,
    x = &quot;Model Random Forest&quot;,
    y = &quot;Prediction Errors&quot;
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text = element_text(color = &quot;grey20&quot;),
    axis.title = element_text(color = &quot;grey20&quot;)
  )</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-43-1.png" width="90%" /></p>
<p>From the plot, the RMSE is predominantly below 7, ranging from
approximately 5.5 to 9. This level of RMSE is lower compared to that of
the linear models we’ve previously evaluated, indicating that this model
performs better. Lower RMSE values signify more accurate predictions,
thus suggesting that this model is a more effective predictor for our
dataset.</p>
<pre class="r"><code># R²
rf_predictions &lt;- predict(rf_model, training_data)
r_squared &lt;- cor(training_data$death_rate, rf_predictions)^2
data.frame(
  model = &quot;Random Forest Model&quot;,
  r.squard = r_squared
) |&gt;
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">model</th>
<th align="right">r.squard</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Random Forest Model</td>
<td align="right">0.9325145</td>
</tr>
</tbody>
</table>
<p>Calculated using the training data, the R² is 0.9325145, which
indicates a very high level of explained variance in the model. This
suggests that our model is highly effective in capturing and
representing the relationships within the training dataset.</p>
</div>
<div id="bootstrap-1" class="section level4">
<h4>Bootstrap</h4>
<p>We perform bootstrapping to evaluate the model’s stability and
reliability.</p>
<pre class="r"><code>library(randomForest)
library(boot)

bootstrap_r2 &lt;- function(data, indices) {
  boot_data &lt;- data[indices, ]
  model &lt;- randomForest(death_rate ~employment+hc_exp+income+edu_level+cardio_rate+smoke_rate+elder_rate, data = boot_data)
  predictions &lt;- predict(model, boot_data)
  r_squared &lt;- cor(boot_data$death_rate, predictions)^2
  return(r_squared)
}

results &lt;- boot(data = training_data, statistic = bootstrap_r2, R = 1000)

# Create a data frame from the bootstrapped R² values
results_df &lt;- data.frame(R_squared = results$t)

# Use ggplot2 to create a histogram with a density curve
ggplot(results_df, aes(x = R_squared)) +
  geom_histogram(aes(y = ..density..), bins = 30, fill = &#39;blue&#39;, alpha = 0.5) +
  geom_density(alpha = .2, fill = &quot;red&quot;) +
  labs(title = &quot;Bootstrap Distribution of R²&quot;, x = &quot;R²&quot;, y = &quot;Density&quot;) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text = element_text(color = &quot;grey20&quot;),
    axis.title = element_text(color = &quot;grey20&quot;)
  )</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-45-1.png" width="90%" /></p>
<p>The bootstrap results of the Random Forest model showing an R² value
around 0.96 indicate a high level of accuracy and consistency. This
suggests that the model is not only effective in explaining a large
portion of the variance in the data but also demonstrates robust
performance across different samples.</p>
</div>
</div>
<div id="prediction" class="section level3">
<h3>Prediction</h3>
<pre class="r"><code>testing_data$predicted_death_rate &lt;- predict(rf_model, testing_data)
ggplot(testing_data, aes(x = death_rate, y = predicted_death_rate)) +
  geom_point(color = &quot;black&quot;) +  # Add the actual data points
  geom_smooth(method = &quot;lm&quot;,se = FALSE, color = &quot;blue&quot;) +  
  labs(title = &quot;Linear Regression Predictions&quot;,
       x = &quot;Actual Values&quot;,
       y = &quot;Predicted Values&quot;) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text = element_text(color = &quot;grey20&quot;),
    axis.title = element_text(color = &quot;grey20&quot;)
  )</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-46-1.png" width="90%" /></p>
<p>Using the 2021 data to predict with the Random Forest model, we
observed that the data points largely align with the fitted line,
especially within the middle range of actual values. There are some
outliers, particularly at higher actual values, but this indicates that
the model’s predictive accuracy is reasonable within the normal
range.</p>
</div>
</div>
<div id="results-and-discussion" class="section level2">
<h2>Results and Discussion</h2>
<pre class="r"><code>importance_values &lt;- importance(rf_model)

feature_importance &lt;- data.frame(Feature = rownames(importance_values), 
                                 Importance = importance_values[,1]) %&gt;%
  arrange(Importance) %&gt;% 
  mutate(Feature = factor(Feature, levels = Feature)) 

plot_ly(feature_importance, x = ~Importance, y = ~Feature, type = &#39;bar&#39;, orientation = &#39;h&#39;) %&gt;%
  layout(title = &quot;Feature Importance from Random Forest Model&quot;,
         xaxis = list(title = &quot;Importance&quot;),
         yaxis = list(title = &quot;Feature&quot;))</code></pre>
<div class="plotly html-widget html-fill-item" id="htmlwidget-da4772625aad0c0700c4" style="width:90%;height:345.6px;"></div>
<script type="application/json" data-for="htmlwidget-da4772625aad0c0700c4">{"x":{"visdat":{"1754e1628be83":["function () ","plotlyVisDat"]},"cur_data":"1754e1628be83","attrs":{"1754e1628be83":{"x":{},"y":{},"orientation":"h","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Feature Importance from Random Forest Model","xaxis":{"domain":[0,1],"automargin":true,"title":"Importance"},"yaxis":{"domain":[0,1],"automargin":true,"title":"Feature","type":"category","categoryorder":"array","categoryarray":["cardio_rate","income","employment","elder_rate","smoke_rate","hc_exp","edu_level"]},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[1187.9888902208124,1238.1395154372374,1414.4543804406962,1471.0246855408136,1505.8696260485719,1778.4947615179824,1888.9695797938891],"y":["cardio_rate","income","employment","elder_rate","smoke_rate","hc_exp","edu_level"],"orientation":"h","type":"bar","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>After careful consideration, we chose the random forest to be our
final mofel. And according to the model, <code>edu_level</code> emerges
as the most important feature, which suggests a strong correlation
between educational attainment and mortality rates in Alzheimer’s
patients. Following it,<code>hc_exp</code> stands as the second most
crucial factor, indicating the importance of healthcare resources in
managing Alzheimer’s disease. Other features like
<code>smoke_rate</code>, <code>elder_rate</code>,
<code>employment</code>, <code>income</code>, and
<code>cardio_rate</code> are ranked in descending order of importance,
indicating a gradual decrease in their significance within the model.
These findings highlight the multifaceted nature of factors affecting
Alzheimer’s patient outcomes and underscore the importance of
socioeconomic and lifestyle factors in addition to healthcare
provision.</p>
</div>
</div>
<div id="clinical-trials" class="section level1">
<h1>Clinical Trials</h1>
<pre class="r"><code># Function to tidy Donanemab results
combine_mean_sd = function(df, group = &quot;&quot;){
  
  n = df |&gt; filter(str_detect(group, &quot;Low/medium tau&quot;)) |&gt; pull(sample_size) # number in group 1
  m =  df |&gt; filter(str_detect(group, &quot;combined&quot;)) |&gt; pull(sample_size) # number in group 2
  sx = df |&gt; filter(str_detect(group, &quot;Low/medium tau&quot;)) |&gt; pull(sd) # sd of group 1
  sy = df |&gt; filter(str_detect(group, &quot;combined&quot;)) |&gt; pull(sd) # sd of group 2
  x_bar = df |&gt; filter(str_detect(group, &quot;Low/medium tau&quot;)) |&gt; pull(mean) # mean of group 1
  y_bar = df |&gt; filter(str_detect(group, &quot;combined&quot;)) |&gt; pull(mean) # mean of group 2

  combined_mean = (n * x_bar + m * y_bar) / (n + m)
  combined_sd =   sqrt(((n-1)*sx^2+(m-1)*sy^2)/(n+m-1)+(n*m*(x_bar-y_bar)^2)/((n+m)*(n+m-1)))
  combined_samplesize = n + m
  combined_ci_lower = combined_mean - 1.96*combined_sd
  combined_ci_upper = combined_mean + 1.96*combined_sd
  
  return (tibble(
    outcome = df |&gt; head(1) |&gt; pull(outcome),
    group = group,
    mean = combined_mean,
    sd = combined_sd,
    sample_size = combined_samplesize,
    ci_lower = combined_ci_lower,
    ci_upper = combined_ci_upper,
    time = 0))}</code></pre>
<div id="clinical-trials-pipeline" class="section level2">
<h2>Clinical Trials Pipeline</h2>
<p>In our quest to deepen the understanding of Alzheimer’s disease and
its treatment landscape, we have developed an innovative Shiny
application designed to visualize the clinical trials of Alzheimer’s
drugs across the United States. This interactive tool is a significant
stride in making complex trial data accessible, which labels all trials
on the map and has regional statistics based on zoom size. The following
screenshot offers a glimpse into the app’s capabilities, and the full
dashboard can be accessed [here].</p>
<p><img src="project_image/shiny_CT1.png" style="width:85%"></p>
</div>
<div id="trials-comparison" class="section level2">
<h2>Trials comparison</h2>
<p>We further evaluate and compare the performance of the two latest
promising drugs Lecanemab and Donanemab for their participants’
characteristics, treatment efficacy, and adverse events.</p>
<div id="participants-demographics" class="section level3">
<h3>Participants’ Demographics</h3>
<pre class="r"><code>sex_df=
  readxl::read_excel(&quot;data/newdrugdemographic.xlsx&quot;,sheet=&quot;Sex&quot;, range = &quot;A1:C5&quot;) |&gt; 
  janitor::clean_names()

race_df=
  readxl::read_excel(&quot;data/newdrugdemographic.xlsx&quot;,sheet=&quot;Race&quot;, range = &quot;A1:C9&quot;) |&gt; 
  janitor::clean_names()

sex_colors &lt;- c(&quot;Male&quot; = &quot;#a1afc9&quot;, &quot;Female&quot; = &quot;#edd1d8&quot;) 
race_colors &lt;- c(&quot;Black&quot; = &quot;#c2ccd0&quot;, &quot;Asian&quot; =&quot;#fcefe8&quot;, &quot;White&quot; = &quot;#e0eee8&quot;, &quot;Other or Missing&quot; = &quot;#eedeb0&quot;) 


p1 &lt;- sex_df |&gt; 
  plot_ly(x = ~drug, y = ~sex_prop, type = &quot;bar&quot;, color = ~sex, colors = sex_colors, legendgroup = &quot;sex&quot;) |&gt; 
  layout(barmode = &quot;stack&quot;,
         showlegend = TRUE) |&gt;
    add_annotations(
    text = &quot;Sex&quot;,
    x = 0.5,
    y = 1.05,
    xref = &quot;paper&quot;,
    yref = &quot;paper&quot;,
    showarrow = FALSE,
    font = list(size = 10)
  )

p2 &lt;- race_df |&gt; 
  mutate(race = fct_reorder(race, -race_prop)) |&gt; 
  plot_ly(x = ~drug, y = ~race_prop, type = &quot;bar&quot;, color = ~race, colors = race_colors, legendgroup = &quot;race&quot;) |&gt; 
  layout(barmode = &quot;stack&quot;,
         showlegend = TRUE) |&gt;
    add_annotations(
    text = &quot;Race&quot;,
    x = 0.5,
    y = 1.05,
    xref = &quot;paper&quot;,
    yref = &quot;paper&quot;,
    showarrow = FALSE,
    font = list(size = 10)
  )

subplot(p1, p2, nrows = 1, margin = 0.05) |&gt;
  layout(title = &quot;Distribution of Baseline Participants&#39; Sex and Race by Drug&quot;,
         yaxis = list(title = &quot;Percentage (%)&quot;))</code></pre>
<div class="plotly html-widget html-fill-item" id="htmlwidget-9b1bc01b27cf12b0e297" style="width:90%;height:345.6px;"></div>
<script type="application/json" data-for="htmlwidget-9b1bc01b27cf12b0e297">{"x":{"data":[{"x":["Lecanemab","Donanemab"],"y":[51.600000000000001,56.5],"legendgroup":"sex","type":"bar","name":"Female","marker":{"color":"rgba(237,209,216,1)","line":{"color":"rgba(237,209,216,1)"}},"textfont":{"color":"rgba(237,209,216,1)"},"error_y":{"color":"rgba(237,209,216,1)"},"error_x":{"color":"rgba(237,209,216,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Lecanemab","Donanemab"],"y":[48.399999999999999,43.5],"legendgroup":"sex","type":"bar","name":"Male","marker":{"color":"rgba(161,175,201,1)","line":{"color":"rgba(161,175,201,1)"}},"textfont":{"color":"rgba(161,175,201,1)"},"error_y":{"color":"rgba(161,175,201,1)"},"error_x":{"color":"rgba(161,175,201,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Lecanemab","Donanemab"],"y":[76.299999999999997,90],"legendgroup":"race","type":"bar","name":"White","marker":{"color":"rgba(224,238,232,1)","line":{"color":"rgba(224,238,232,1)"}},"textfont":{"color":"rgba(224,238,232,1)"},"error_y":{"color":"rgba(224,238,232,1)"},"error_x":{"color":"rgba(224,238,232,1)"},"xaxis":"x2","yaxis":"y2","frame":null},{"x":["Lecanemab","Donanemab"],"y":[17.100000000000001,7.2999999999999998],"legendgroup":"race","type":"bar","name":"Asian","marker":{"color":"rgba(252,239,232,1)","line":{"color":"rgba(252,239,232,1)"}},"textfont":{"color":"rgba(252,239,232,1)"},"error_y":{"color":"rgba(252,239,232,1)"},"error_x":{"color":"rgba(252,239,232,1)"},"xaxis":"x2","yaxis":"y2","frame":null},{"x":["Lecanemab","Donanemab"],"y":[2.2999999999999998,2.5],"legendgroup":"race","type":"bar","name":"Black","marker":{"color":"rgba(194,204,208,1)","line":{"color":"rgba(194,204,208,1)"}},"textfont":{"color":"rgba(194,204,208,1)"},"error_y":{"color":"rgba(194,204,208,1)"},"error_x":{"color":"rgba(194,204,208,1)"},"xaxis":"x2","yaxis":"y2","frame":null},{"x":["Lecanemab","Donanemab"],"y":[4.2999999999999998,0.20000000000000001],"legendgroup":"race","type":"bar","name":"Other or Missing","marker":{"color":"rgba(238,222,176,1)","line":{"color":"rgba(238,222,176,1)"}},"textfont":{"color":"rgba(238,222,176,1)"},"error_y":{"color":"rgba(238,222,176,1)"},"error_x":{"color":"rgba(238,222,176,1)"},"xaxis":"x2","yaxis":"y2","frame":null}],"layout":{"xaxis":{"domain":[0,0.45000000000000001],"automargin":true,"type":"category","categoryorder":"array","categoryarray":["Donanemab","Lecanemab"],"anchor":"y"},"xaxis2":{"domain":[0.55000000000000004,1],"automargin":true,"type":"category","categoryorder":"array","categoryarray":["Donanemab","Lecanemab"],"anchor":"y2"},"yaxis2":{"domain":[0,1],"automargin":true,"anchor":"x2"},"yaxis":{"domain":[0,1],"automargin":true,"anchor":"x","title":"Percentage (%)"},"annotations":[{"text":"Sex","x":0.22500000000000001,"y":1.05,"xref":"paper","yref":"paper","showarrow":false,"font":{"size":10}},{"text":"Race","x":0.77500000000000002,"y":1.05,"xref":"paper","yref":"paper","showarrow":false,"font":{"size":10}}],"shapes":[],"images":[],"margin":{"b":40,"l":60,"t":25,"r":10},"barmode":"stack","showlegend":true,"hovermode":"closest","title":"Distribution of Baseline Participants' Sex and Race by Drug"},"attrs":{"1754e76663389":{"x":{},"y":{},"legendgroup":"sex","color":{},"colors":["#a1afc9","#edd1d8"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"},"1754e2fc1a419":{"x":{},"y":{},"legendgroup":"race","color":{},"colors":["#c2ccd0","#fcefe8","#e0eee8","#eedeb0"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"subplot":true,"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<ul>
<li><p>From the plot, we can see that there are more female participants
in Donanemab’s clinical trial that in Lecanemab’s clinical
trial.</p></li>
<li><p>From the plot, we can also see there is more diversity in
Lecanemab’s clinical trial. Races other than white occupy a larger
proportion of participants in Lecanemab’s clinical trial than in
Donanemab’s clinical trial than that in Lecanemab’s clinical trial,
especially Asians.</p></li>
</ul>
<p>All trials participants took Alzheimer’s tests to evaluate their
stages at the start of study. CDR-SB (Clinical Dementia Rating Scale Sum
of Boxes), ADAS-Cog (Alzheimer’s Disease Assessment Scale - Cognitive
Subscale) and MMSE (Mini-mental state examination) were shown in the
plot, details of theses test scores were explained in next part.</p>
<pre class="r"><code>iADRS &lt;- read_excel(&quot;data/Donanemab_.xlsx&quot;, sheet = &quot;1&quot;)
CDR_SB &lt;- read_excel(&quot;data/Donanemab_.xlsx&quot;, sheet = &quot;2&quot;)
ADCS_iADL &lt;- read_excel(&quot;data/Donanemab_.xlsx&quot;, sheet = &quot;3&quot;)
ADAS_Cog13 &lt;- read_excel(&quot;data/Donanemab_.xlsx&quot;, sheet = &quot;4&quot;)
MMSE &lt;- read_excel(&quot;data/Donanemab_.xlsx&quot;, sheet = &quot;5&quot;)

lec_result &lt;- read_excel(&quot;data/Lecanemab.xlsx&quot;, sheet = &quot;result&quot;) |&gt;
  filter(time == 0,
         outcome %in% c(&quot;CDR-SB&quot;, &quot;ADAS-Cog14&quot;, &quot;MMSE&quot;)) |&gt;
  mutate(drug = &quot;Lecanemab&quot;,
         ci_lower = mean - 1.96*sd,
         ci_upper = mean + 1.96*sd) |&gt;
  select(drug, everything())

don_result = bind_rows(
  combine_mean_sd(CDR_SB |&gt; filter(time == 0, str_detect(group, &quot;Donanemab&quot;)), &quot;Donanemab&quot;),
  combine_mean_sd(CDR_SB |&gt; filter(time == 0, str_detect(group, &quot;Placebo&quot;)), &quot;Placebo&quot;),
  combine_mean_sd(ADAS_Cog13 |&gt; filter(time == 0, str_detect(group, &quot;Donanemab&quot;)), &quot;Donanemab&quot;),
  combine_mean_sd(ADAS_Cog13 |&gt; filter(time == 0, str_detect(group, &quot;Placebo&quot;)), &quot;Placebo&quot;),
  combine_mean_sd(MMSE |&gt; filter(time == 0, str_detect(group, &quot;Donanemab&quot;)), &quot;Donanemab&quot;),
  combine_mean_sd(MMSE |&gt; filter(time == 0, str_detect(group, &quot;Placebo&quot;)), &quot;Placebo&quot;)
  ) |&gt;
  mutate(drug = &quot;Donanemab&quot;) |&gt;
  select(drug, everything())


ggplot(bind_rows(lec_result, don_result) |&gt; filter (!(outcome %in% c(&quot;CDR-SB&quot;, &quot;MMSE&quot;) &amp; group == &quot;Placebo&quot;)), aes(x = as.factor(time), y = mean, fill = group, color = group)) +
  geom_point(position = position_dodge(0.9), size = 3, alpha = 0.7) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), position = position_dodge(0.9), width = 0.25) +
  facet_wrap(~outcome, scales = &quot;free_y&quot;) +
  labs(title = &quot;Mean with 95% CI at Baseline&quot;,
       x = &quot;Time&quot;,
       y = &quot;Mean&quot;) +
  theme_minimal()</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-51-1.png" width="90%" /></p>
</div>
<div id="treatment-evaluation" class="section level3">
<h3>Treatment evaluation</h3>
<p>The evaluated outcomes encompassed measures such as CDR-SB (Clinical
Dementia Rating Scale Sum of Boxes), ADAS-Cog (Alzheimer’s Disease
Assessment Scale - Cognitive Subscale), and various other clinical
assessments. These metrics collectively offer valuable insights into the
effectiveness of donanemab in comparison to the placebo, shedding light
on its impact on slowing the progression of Alzheimer’s disease over the
76-week (18 months) trial period.</p>
<p>In the trial of Donanemab, participants were categorized into two
groups based on tau biomarker levels in their cerebrospinal fluid (CSF):
those with low/medium tau (mild cognitive impairment or early
Alzheimer’s with lower tau levels) and those with high tau (early
Alzheimer’s with higher tau levels). Additionally, a combined population
included all trial participants, irrespective of tau levels. This
stratification aimed to evaluate the efficacy of donanemab across
different Alzheimer’s patient subgroups.</p>
<div id="cdr-sb" class="section level4">
<h4>CDR-SB</h4>
<p>The Clinical Dementia Rating Scale Sum of Boxes (CDR-SB) is a widely
used assessment tool for evaluating the severity of dementia. It is a
composite score derived from the Clinical Dementia Rating (CDR) scale,
which is used to assess the cognitive and functional abilities of
individuals with dementia.</p>
<p>The CDR-SB incorporates ratings across six domains: memory,
orientation, judgment and problem solving, community affairs, home and
hobbies, and personal care. Each domain is rated on a scale from 0 (no
impairment) to 3 (severe impairment), and the total CDR-SB score ranges
from 0 to 18, with higher scores indicating greater clinical
impairment.</p>
<pre class="r"><code>Don_CDR_SB = read_excel(&quot;data/Donanemab.xlsx&quot;, sheet = &quot;result&quot;) |&gt;
  filter(outcome == &quot;CDR-SB&quot;,
         str_detect(group, &quot;combined&quot;))

Lec_CDR_SB = read_excel(&quot;data/Lecanemab.xlsx&quot;, sheet = &quot;result&quot;) |&gt;
  filter(outcome == &quot;CDR-SB&quot;)

CDR_SB_merge = bind_rows(Don_CDR_SB, Lec_CDR_SB) |&gt;
  mutate(group = case_match(
    group,
    &quot;Donanemab-combined&quot; ~ &quot;Donanemab-combined&quot;,
    &quot;Placebo-combined&quot; ~ &quot;Donanemab Placebo-combined&quot;,
    &quot;Lecanemab&quot; ~ &quot;Lecanemab&quot;,
    &quot;Placebo&quot; ~ &quot;Lecanemab Placebo&quot;))

ggplot(CDR_SB_merge, aes(x = as.factor(time), y = mean, fill = group, color = group)) +
  geom_point(position = position_dodge(0.9), size = 3, alpha = 0.7) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), position = position_dodge(0.9), width = 0.25) +
  labs(title = &quot;Mean with 95% CI over Time (CDR-SB)&quot;,
       x = &quot;Time&quot;,
       y = &quot;Mean&quot;) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-52-1.png" width="90%" /></p>
<ul>
<li>The trial results demonstrated that both treatments slows the
clinical progression of Alzheimer compared to their placebo as measured
by the CDR-SB, indicating its potential efficacy in addressing the
symptoms and functional decline associated with early symptomatic
Alzheimer’s disease. Lecanemab shows adjusted mean change of 1.21 from
baseline to endpoint, while Donanemab shows 1.16 (95%CI: 0.97-1.35)
least square mean change.</li>
</ul>
</div>
<div id="adas-cog" class="section level4">
<h4>ADAS-Cog</h4>
<p>The ADAS-Cog, a primary cognitive outcome measure mandated by the FDA
for Alzheimer’s drug trials in the U.S., assesses language, memory,
praxis, and orientation. This test, taking 30-35 minutes, scores from
0-70, with higher scores indicating greater cognitive impairment.</p>
<pre class="r"><code>Don_ADAS_Cog  = read_excel(&quot;data/Donanemab.xlsx&quot;, sheet = &quot;result&quot;) |&gt;
  filter(outcome == &quot;ADAS-Cog13&quot;)

Lec_ADAS_Cog = read_excel(&quot;data/Lecanemab.xlsx&quot;, sheet = &quot;result&quot;) |&gt;
  filter(outcome == &quot;ADAS-Cog14&quot;)

ADAS_Cog_merge = bind_rows(Don_ADAS_Cog, Lec_ADAS_Cog) |&gt;
  mutate(group = case_match(
    group,
    &quot;Donanemab-combined&quot; ~ &quot;Donanemab (combined)&quot;,
    &quot;Placebo-combined&quot; ~ &quot;Donanemab Placebo (combined)&quot;,
    &quot;Lecanemab&quot; ~ &quot;Lecanemab&quot;,
    &quot;Placebo&quot; ~ &quot;Lecanemab Placebo&quot;,
    &quot;Donanemab-Low/medium tau&quot; ~ &quot;Donanemab (Low/medium tau)&quot;,
    &quot;Placebo-Low/medium tau&quot; ~ &quot;Donanemab Placebo (Low/medium tau)&quot;))

ggplot(ADAS_Cog_merge, aes(x = as.factor(time), y = mean, fill = group, color = group)) +
  geom_point(position = position_dodge(0.9), size = 3, alpha = 0.7) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), position = position_dodge(0.9), width = 0.25) +
  labs(title = &quot;Mean with 95% CI over Time (ADAS-Cog)&quot;,
       x = &quot;Time&quot;,
       y = &quot;Mean&quot;) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-53-1.png" width="90%" /></p>
<ul>
<li>A more pronounced reduction in the mean change from baseline to
endpoint in the treatment group, as compared to the placebo, was
observed for both Lecanemab (4.14 adjusted mean change) and Donanemab
(3.17 LSM for low/medium tau, 5.46 LSM for combined). This suggests a
potential positive impact of these drugs on cognitive function in
Alzheimer’s patients, with varying efficacy across different stages of
the disease.</li>
</ul>
</div>
</div>
<div id="survival-analysis" class="section level3">
<h3>Survival Analysis</h3>
<p>The Phase III trials of Lecanemab and Donanemab both use cumulative
hazard ratio to indicate the risk of progression assessed using CDR-SB
score. The hazard plot for Donanemab is as following</p>
<pre class="r"><code>Don_KM = 
  read_excel(&quot;./Data/Donanemab.xlsx&quot;, sheet = &quot;K-M&quot;, range = &quot;A1:D16&quot;) |&gt;
  janitor::clean_names()

plot_ly(Don_KM |&gt;
                 filter(test == &quot;CDR-SB&quot;) |&gt;
                 pivot_longer(
                   donanemab:placebo,
                   names_to = &quot;drug&quot;,
                   values_to = &quot;ratio&quot;
                 ), x = ~time, y = ~ratio, color = ~drug, line = list(shape = &quot;hv&quot;), colors = &quot;viridis&quot;) |&gt;
  layout(title = &quot;Hazard Plot for Donanemab&quot;,
             xaxis = list(title = &quot;Days from First Infusion&quot;),
             yaxis = list(title = &quot;Percentage of Participants Progression&quot;))</code></pre>
<div class="plotly html-widget html-fill-item" id="htmlwidget-481e7dcfc0aa0beb142f" style="width:90%;height:345.6px;"></div>
<script type="application/json" data-for="htmlwidget-481e7dcfc0aa0beb142f">{"x":{"visdat":{"1754e52dd9f77":["function () ","plotlyVisDat"]},"cur_data":"1754e52dd9f77","attrs":{"1754e52dd9f77":{"x":{},"y":{},"line":{"shape":"hv"},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20]}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Hazard Plot for Donanemab","xaxis":{"domain":[0,1],"automargin":true,"title":"Days from First Infusion"},"yaxis":{"domain":[0,1],"automargin":true,"title":"Percentage of Participants Progression"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[0,60,120,180,240,360,480,540],"y":[0,0,0.035000000000000003,0.070000000000000007,0.078,0.154,0.26300000000000001,0.26300000000000001],"line":{"color":"rgba(68,1,84,1)","shape":"hv"},"type":"scatter","mode":"markers+lines","name":"donanemab","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[0,60,120,180,240,360,480,540],"y":[0,0,0.081000000000000003,0.14999999999999999,0.17000000000000001,0.246,0.38700000000000001,0.38700000000000001],"line":{"color":"rgba(253,231,37,1)","shape":"hv"},"type":"scatter","mode":"markers+lines","name":"placebo","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<ul>
<li>The hazard ratio for the combined group of Donanemab was found to be
0.623 with a 95% confidence interval of 0.519 to 0.748, indicating a
significant reduction in the risk associated with the progression of
Alzheimer’s disease as measured by the CDR-SB score. In comparison,
Lecanemab demonstrated a hazard ratio of 0.69, also suggesting a reduced
risk, albeit to a slightly lesser extent than Donanemab. These results
indicate that both drugs are effective in slowing the progression of
Alzheimer’s disease, with Donanemab showing a marginally higher efficacy
in this regard.</li>
</ul>
</div>
<div id="adverse-events" class="section level3">
<h3>Adverse Events</h3>
<div id="general-overview" class="section level4">
<h4>General Overview</h4>
<p>As we progress in our comprehensive exploration of Alzheimer’s
disease and its treatment options, we now turn our focus to a critical
aspect of drug evaluation: the analysis of adverse events associated
with the two promising drugs.</p>
<pre class="r"><code>lec_safety = read_excel(&quot;./Data/Lecanemab.xlsx&quot;, sheet = &quot;safety&quot;, range = &quot;A1:C5&quot;) |&gt;
  janitor::clean_names()

don_safety = read_excel(&quot;./Data/Donanemab.xlsx&quot;, sheet = &quot;safety&quot;, range = &quot;A1:C5&quot;) |&gt;
  janitor::clean_names()

merge_safety = left_join(lec_safety, don_safety, by = &quot;events&quot;)</code></pre>
<pre class="r"><code>plot_ly(merge_safety |&gt;
  mutate(events = fct_reorder(events, -lecanemab)) |&gt;
  pivot_longer(
    lecanemab:donanemab_placebo,
    names_to = &quot;drug&quot;,
    values_to = &quot;cases&quot;
  ), 
  x = ~events, y = ~cases, color = ~drug, type = &#39;bar&#39;, colors = &quot;viridis&quot;)  |&gt;
  layout(title = &quot;Barplot for Adverse Events&quot;,
             xaxis = list(title = &quot;Adverse Event&quot;),
             yaxis = list(title = &quot;Number of participants&quot;))</code></pre>
<div class="plotly html-widget html-fill-item" id="htmlwidget-b014912348a2281c4b6d" style="width:90%;height:345.6px;"></div>
<script type="application/json" data-for="htmlwidget-b014912348a2281c4b6d">{"x":{"visdat":{"1754e1ae4039":["function () ","plotlyVisDat"]},"cur_data":"1754e1ae4039","attrs":{"1754e1ae4039":{"x":{},"y":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Barplot for Adverse Events","xaxis":{"domain":[0,1],"automargin":true,"title":"Adverse Event","type":"category","categoryorder":"array","categoryarray":["Participants with ≥1 AEs","Participants with ≥1 serious Aes","Study discontinuations due to AEs","Death"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Number of participants"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["Participants with ≥1 AEs","Participants with ≥1 serious Aes","Study discontinuations due to AEs","Death"],"y":[759,148,69,16],"type":"bar","name":"donanemab","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Participants with ≥1 AEs","Participants with ≥1 serious Aes","Study discontinuations due to AEs","Death"],"y":[718,138,32,10],"type":"bar","name":"donanemab_placebo","marker":{"color":"rgba(49,104,142,1)","line":{"color":"rgba(49,104,142,1)"}},"textfont":{"color":"rgba(49,104,142,1)"},"error_y":{"color":"rgba(49,104,142,1)"},"error_x":{"color":"rgba(49,104,142,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Participants with ≥1 AEs","Participants with ≥1 serious Aes","Study discontinuations due to AEs","Death"],"y":[798,126,62,6],"type":"bar","name":"lecanemab","marker":{"color":"rgba(53,183,121,1)","line":{"color":"rgba(53,183,121,1)"}},"textfont":{"color":"rgba(53,183,121,1)"},"error_y":{"color":"rgba(53,183,121,1)"},"error_x":{"color":"rgba(53,183,121,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Participants with ≥1 AEs","Participants with ≥1 serious Aes","Study discontinuations due to AEs","Death"],"y":[735,101,26,7],"type":"bar","name":"lecanemab_placebo","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<ul>
<li><p>The Lecanemab group experienced a 0.7% death rate (6 cases)
compared to 0.8% (7 cases) in the placebo group, with no deaths linked
to Lecanemab or ARIA. Serious adverse events were slightly higher in the
Lecanemab group at 14.0% (126 cases) versus 11.3% (101 cases) in the
placebo.</p></li>
<li><p>For Donanemab, the death rate was 1.9% (16 cases) in the
treatment group against 1.1% (10 cases) in the placebo, with serious
adverse events at 17.4% (148 cases) for Donanemab and 15.8% (138 cases)
for the placebo. These results suggest a similar safety profile for both
drugs compared to their respective placebo groups.</p></li>
</ul>
<pre class="r"><code>safety_test = function(a, b, c, d, n1, n2){
  RD = round(a/n1 - b/n2, 4)
  RR = round((a/n1)/(b/n2), 4)
  OR = round((a*d)/(b*c), 4)
  Chis = round(prop.test(x = c(a, b), n = c(c, d), alternative = &quot;two.sided&quot;, correct = FALSE)$statistic, 4)
  p_value = round(prop.test(x = c(a, b), n = c(n1, n2), alternative = &quot;two.sided&quot;, correct = FALSE)$p.value, 6)
  return (tibble(Risk_Diff = RD, Risk_Ratio = RR, Odds_Ratio = OR, Xsquared = Chis, P.value = p_value))
  }</code></pre>
<pre class="r"><code>lec_safety_test = safety_test(126, 101, 772, 796, 898, 897)
don_safety_test = safety_test(148, 138, 705, 736, 853, 874)
comp_safety_test = safety_test(126, 148, 772, 705, 898, 853)
safety_merge = bind_rows(lec_safety_test, don_safety_test, comp_safety_test) |&gt;
  mutate(Test = c(&quot;Lec vs Placebo&quot;, &quot;Don vs Placebo&quot;, &quot;Lec vs Don&quot;)) |&gt;
  select(Test, everything())

kable(safety_merge)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Test</th>
<th align="right">Risk_Diff</th>
<th align="right">Risk_Ratio</th>
<th align="right">Odds_Ratio</th>
<th align="right">Xsquared</th>
<th align="right">P.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Lec vs Placebo</td>
<td align="right">0.0277</td>
<td align="right">1.2461</td>
<td align="right">1.2863</td>
<td align="right">4.1774</td>
<td align="right">0.077332</td>
</tr>
<tr class="even">
<td align="left">Don vs Placebo</td>
<td align="right">0.0156</td>
<td align="right">1.0989</td>
<td align="right">1.1196</td>
<td align="right">1.1387</td>
<td align="right">0.382920</td>
</tr>
<tr class="odd">
<td align="left">Lec vs Don</td>
<td align="right">-0.0332</td>
<td align="right">0.8087</td>
<td align="right">0.7775</td>
<td align="right">5.3225</td>
<td align="right">0.056015</td>
</tr>
</tbody>
</table>
<p>In our statistical analysis of serious adverse events associated with
Lecanemab, Donanemab, and their placebos, we have identified key
findings. With a significance level set at 0.1, our results indicate a
significant difference in serious adverse events between Lecanemab and
its placebo, suggesting a higher risk associated with Lecanemab. In
contrast, Donanemab did not show a significant difference in serious
adverse events compared to its placebo, implying a potentially safer
profile. Additionally, a significant difference was observed between
Lecanemab and Donanemab, highlighting distinct safety profiles for these
drugs.</p>
<p>Then, we further investigate the differences of specific adverse
events for two drugs.</p>
<pre class="r"><code>lec_ae = read_excel(&quot;./Data/Lecanemab.xlsx&quot;, sheet = &quot;AE&quot;, range = &quot;A1:C10&quot;) |&gt;
  janitor::clean_names()

don_ae = read_excel(&quot;./Data/Donanemab.xlsx&quot;, sheet = &quot;AE&quot;, range = &quot;A1:C10&quot;) |&gt;
  janitor::clean_names()

merge_ae = left_join(lec_ae, don_ae, by = &quot;ae&quot;)</code></pre>
<pre class="r"><code>plot_ly(merge_ae |&gt;
  mutate(ae = fct_reorder(ae, donanemab)) |&gt;
  pivot_longer(
    lecanemab:donanemab_placebo,
    names_to = &quot;drug&quot;,
    values_to = &quot;cases&quot;
  ), 
  x = ~ae, y = ~cases, color = ~drug, type = &#39;bar&#39;, colors = &quot;viridis&quot;)  |&gt;
  layout(title = &quot;Barplot for Adverse Events&quot;,
             xaxis = list(title = &quot;Adverse Event&quot;),
             yaxis = list(title = &quot;Number of participants&quot;))</code></pre>
<div class="plotly html-widget html-fill-item" id="htmlwidget-a8d8d9aa55b801847b94" style="width:90%;height:345.6px;"></div>
<script type="application/json" data-for="htmlwidget-a8d8d9aa55b801847b94">{"x":{"visdat":{"1754e5a33952d":["function () ","plotlyVisDat"]},"cur_data":"1754e5a33952d","attrs":{"1754e5a33952d":{"x":{},"y":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Barplot for Adverse Events","xaxis":{"domain":[0,1],"automargin":true,"title":"Adverse Event","type":"category","categoryorder":"array","categoryarray":["Diarrhea","Urinary tract infection","Arrthralgia","Dizziness","Infusion-related reaction","Fall","Headache","ARIA-H","ARIA-E"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Number of participants"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["Infusion-related reaction","ARIA-E","ARIA-H","Headache","Fall","Urinary tract infection","Arrthralgia","Dizziness","Diarrhea"],"y":[74,205,168,119,114,45,49,53,43],"type":"bar","name":"donanemab","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Infusion-related reaction","ARIA-E","ARIA-H","Headache","Fall","Urinary tract infection","Arrthralgia","Dizziness","Diarrhea"],"y":[4,17,65,86,110,59,42,48,50],"type":"bar","name":"donanemab_placebo","marker":{"color":"rgba(49,104,142,1)","line":{"color":"rgba(49,104,142,1)"}},"textfont":{"color":"rgba(49,104,142,1)"},"error_y":{"color":"rgba(49,104,142,1)"},"error_x":{"color":"rgba(49,104,142,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Infusion-related reaction","ARIA-E","ARIA-H","Headache","Fall","Urinary tract infection","Arrthralgia","Dizziness","Diarrhea"],"y":[237,113,155,100,93,78,53,49,48],"type":"bar","name":"lecanemab","marker":{"color":"rgba(53,183,121,1)","line":{"color":"rgba(53,183,121,1)"}},"textfont":{"color":"rgba(53,183,121,1)"},"error_y":{"color":"rgba(53,183,121,1)"},"error_x":{"color":"rgba(53,183,121,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Infusion-related reaction","ARIA-E","ARIA-H","Headache","Fall","Urinary tract infection","Arrthralgia","Dizziness","Diarrhea"],"y":[66,15,81,73,86,82,62,46,58],"type":"bar","name":"lecanemab_placebo","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>The barplot clearly shows notable differences in specific adverse
events (such as Infusion-related reactions, ARIA-E/ARIA-H, Urinary tract
infections, and Headaches) between the treatment and placebo groups. To
further evaluate and quantify these observed differences, we will
proceed with a detailed statistical tests to provide a more definitive
understanding of the significance of these adverse events.</p>
</div>
<div id="lecanemab-vs-placebo" class="section level4">
<h4>Lecanemab vs Placebo</h4>
<pre class="r"><code># test = lec_ae |&gt;
#   mutate(p = lecanemab_placebo/sum(lecanemab_placebo))
# chisq.test(test$lecanemab, p = test$p, correct = FALSE) \
lec_ae_result = lec_ae |&gt;
  mutate(testresult = map2(lecanemab, lecanemab_placebo, \(a, b) safety_test(a, b, 898-a, 897-b, 898, 897))) |&gt;
  rename(Adverse_Effect = ae) |&gt;
  unnest(testresult) |&gt;
  select(-lecanemab, -lecanemab_placebo)

kable(lec_ae_result)</code></pre>
<table>
<colgroup>
<col width="34%" />
<col width="13%" />
<col width="14%" />
<col width="14%" />
<col width="11%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Adverse_Effect</th>
<th align="right">Risk_Diff</th>
<th align="right">Risk_Ratio</th>
<th align="right">Odds_Ratio</th>
<th align="right">Xsquared</th>
<th align="right">P.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Infusion-related reaction</td>
<td align="right">0.1903</td>
<td align="right">3.5869</td>
<td align="right">4.5144</td>
<td align="right">177.2332</td>
<td align="right">0.000000</td>
</tr>
<tr class="even">
<td align="left">ARIA-E</td>
<td align="right">0.1091</td>
<td align="right">7.5249</td>
<td align="right">8.4642</td>
<td align="right">94.4143</td>
<td align="right">0.000000</td>
</tr>
<tr class="odd">
<td align="left">ARIA-H</td>
<td align="right">0.0823</td>
<td align="right">1.9114</td>
<td align="right">2.1016</td>
<td align="right">36.1979</td>
<td align="right">0.000000</td>
</tr>
<tr class="even">
<td align="left">Headache</td>
<td align="right">0.0300</td>
<td align="right">1.3683</td>
<td align="right">1.4145</td>
<td align="right">5.7372</td>
<td align="right">0.031416</td>
</tr>
<tr class="odd">
<td align="left">Fall</td>
<td align="right">0.0077</td>
<td align="right">1.0802</td>
<td align="right">1.0895</td>
<td align="right">0.3691</td>
<td align="right">0.586741</td>
</tr>
<tr class="even">
<td align="left">Urinary tract infection</td>
<td align="right">-0.0046</td>
<td align="right">0.9502</td>
<td align="right">0.9454</td>
<td align="right">0.1396</td>
<td align="right">0.734818</td>
</tr>
<tr class="odd">
<td align="left">Arrthralgia</td>
<td align="right">-0.0101</td>
<td align="right">0.8539</td>
<td align="right">0.8447</td>
<td align="right">0.8755</td>
<td align="right">0.382293</td>
</tr>
<tr class="even">
<td align="left">Dizziness</td>
<td align="right">0.0033</td>
<td align="right">1.0640</td>
<td align="right">1.0677</td>
<td align="right">0.1080</td>
<td align="right">0.756031</td>
</tr>
<tr class="odd">
<td align="left">Diarrhea</td>
<td align="right">-0.0112</td>
<td align="right">0.8267</td>
<td align="right">0.8169</td>
<td align="right">1.1504</td>
<td align="right">0.313832</td>
</tr>
</tbody>
</table>
<ul>
<li>The statistical tests reveals significant differences in the
incidence of infusion-related reactions, ARIA-E/ARIA-H, and headaches
between the Lecanemab and placebo groups. These findings are consistent
with the most common side effects listed on the Lecanemab website,
validating our results. This highlights the need for careful monitoring
of these specific adverse events when considering Lecanemab for
Alzheimer’s treatment, ensuring informed decision-making and optimized
patient care.</li>
</ul>
</div>
<div id="donanemab-vs-placebo" class="section level4">
<h4>Donanemab vs Placebo</h4>
<pre class="r"><code># test = don_ae |&gt;
#   mutate(p = donanemab_placebo/sum(donanemab_placebo))
# chisq.test(test$donanemab, p = test$p, correct = FALSE)

don_ae_result = don_ae |&gt;
  mutate(testresult = map2(donanemab, donanemab_placebo, \(a, b) safety_test(a, b, 853-a, 874-b, 853, 874))) |&gt;
  rename(Adverse_Effect = ae) |&gt;
  unnest(testresult) |&gt;
  select(-donanemab, -donanemab_placebo)

kable(don_ae_result)</code></pre>
<table>
<colgroup>
<col width="34%" />
<col width="13%" />
<col width="14%" />
<col width="14%" />
<col width="11%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Adverse_Effect</th>
<th align="right">Risk_Diff</th>
<th align="right">Risk_Ratio</th>
<th align="right">Odds_Ratio</th>
<th align="right">Xsquared</th>
<th align="right">P.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Infusion-related reaction</td>
<td align="right">0.0822</td>
<td align="right">18.9555</td>
<td align="right">20.6611</td>
<td align="right">74.5253</td>
<td align="right">0.000000</td>
</tr>
<tr class="even">
<td align="left">ARIA-E</td>
<td align="right">0.2209</td>
<td align="right">12.3557</td>
<td align="right">15.9482</td>
<td align="right">258.0030</td>
<td align="right">0.000000</td>
</tr>
<tr class="odd">
<td align="left">ARIA-H</td>
<td align="right">0.1226</td>
<td align="right">2.6482</td>
<td align="right">3.0525</td>
<td align="right">76.6319</td>
<td align="right">0.000000</td>
</tr>
<tr class="even">
<td align="left">Headache</td>
<td align="right">0.0411</td>
<td align="right">1.4178</td>
<td align="right">1.4855</td>
<td align="right">9.1550</td>
<td align="right">0.008271</td>
</tr>
<tr class="odd">
<td align="left">Fall</td>
<td align="right">0.0078</td>
<td align="right">1.0619</td>
<td align="right">1.0714</td>
<td align="right">0.3132</td>
<td align="right">0.630088</td>
</tr>
<tr class="even">
<td align="left">Urinary tract infection</td>
<td align="right">-0.0148</td>
<td align="right">0.7815</td>
<td align="right">0.7693</td>
<td align="right">1.8867</td>
<td align="right">0.197644</td>
</tr>
<tr class="odd">
<td align="left">Arrthralgia</td>
<td align="right">0.0094</td>
<td align="right">1.1954</td>
<td align="right">1.2073</td>
<td align="right">0.8524</td>
<td align="right">0.382567</td>
</tr>
<tr class="even">
<td align="left">Dizziness</td>
<td align="right">0.0072</td>
<td align="right">1.1314</td>
<td align="right">1.1401</td>
<td align="right">0.4621</td>
<td align="right">0.523000</td>
</tr>
<tr class="odd">
<td align="left">Diarrhea</td>
<td align="right">-0.0068</td>
<td align="right">0.8812</td>
<td align="right">0.8749</td>
<td align="right">0.4388</td>
<td align="right">0.531494</td>
</tr>
</tbody>
</table>
<ul>
<li>The test for comparing Donanemab and its placebo group has similarly
identified significant differences in the occurrence of infusion-related
reactions, ARIA-E/ARIA-H, and headaches. This parallel finding with
Donanemab, mirroring the results observed with Lecanemab, underscores
the importance of these specific adverse events in the context of
Alzheimer’s disease treatments.</li>
</ul>
</div>
<div id="lecanemab-vs-donanemab" class="section level4">
<h4>Lecanemab vs Donanemab</h4>
<pre class="r"><code># test = don_ae |&gt;
#   mutate(p = donanemab_placebo/sum(donanemab_placebo))
# chisq.test(lec_ae$lecanemab, p = test$p, correct = FALSE) 
com_ae =  don_ae |&gt;
  mutate(lecanemab = lec_ae$lecanemab) |&gt;
  select(-donanemab_placebo)

com_ae_test = com_ae |&gt;
  mutate(testresult = map2(lecanemab, donanemab, \(a, b) safety_test(a, b, 898-a, 853-b, 898, 853))) |&gt;
  rename(Adverse_Effect = ae) |&gt;
  unnest(testresult) |&gt;
  select(-donanemab, -lecanemab) |&gt;
  filter(P.value &lt; 0.05)

kable(com_ae_test)</code></pre>
<table>
<colgroup>
<col width="34%" />
<col width="13%" />
<col width="14%" />
<col width="14%" />
<col width="11%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Adverse_Effect</th>
<th align="right">Risk_Diff</th>
<th align="right">Risk_Ratio</th>
<th align="right">Odds_Ratio</th>
<th align="right">Xsquared</th>
<th align="right">P.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Infusion-related reaction</td>
<td align="right">0.1772</td>
<td align="right">3.0422</td>
<td align="right">3.7744</td>
<td align="right">146.6853</td>
<td align="right">0.000000</td>
</tr>
<tr class="even">
<td align="left">ARIA-E</td>
<td align="right">-0.1145</td>
<td align="right">0.5236</td>
<td align="right">0.4550</td>
<td align="right">61.1095</td>
<td align="right">0.000000</td>
</tr>
<tr class="odd">
<td align="left">Urinary tract infection</td>
<td align="right">0.0341</td>
<td align="right">1.6465</td>
<td align="right">1.7080</td>
<td align="right">9.0587</td>
<td align="right">0.005251</td>
</tr>
</tbody>
</table>
<ul>
<li>In our comparative analysis of Lecanemab and Donanemab, we found
notable differences in specific adverse events. Lecanemab showed a
higher proportion of infusion-related reactions and urinary tract
infections, while Donanemab exhibited a higher incidence of ARIA-E.
These results highlight the distinct safety profiles of each drug,
emphasizing the need for tailored monitoring strategies based on the
unique risks associated with each treatment in managing Alzheimer’s
disease.</li>
</ul>
</div>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
